#!/bin/bash

get_prop() {
  local prop="$1";
  grep -m1 -Po "^${prop}\s*=\s*\K.*$" /etc/harmony-ap/domibus.properties 2>/dev/null || echo ""
}
. /usr/share/debconf/confmodule

if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ]; then

  if [[ -z "${USE_DYNAMIC}" ]]; then
    db_input high harmony-ap/usedynamicdiscovery
    db_go
  else 
    db_set harmony-ap/usedynamicdiscovery "$USE_DYNAMIC"
    USEDYNAMIC=$USE_DYNAMIC
  fi

  if [ "$USEDYNAMIC" = true ]; then
    if [[ -z "${SML_ZONE}" ]]; then
      db_input high harmony-ap/smlzone
      db_go
    else 
      db_set harmony-ap/smlzone "$SML_ZONE"
    fi
  fi

  db_beginblock
  if [[ -z "${ADM_USER}" ]]; then
    db_input high harmony-ap/adminuser || true
  else 
    db_set harmony-ap/adminuser "$ADM_USER"
  fi
  if [[ -z "${ADM_PASS}" ]]; then
    db_input high harmony-ap/adminpassword || true
  else 
    db_set harmony-ap/adminpassword "$ADM_PASS"
  fi
  if [[ -z "${PARTY_NAME}" ]]; then
    db_input high harmony-ap/partyname || true
  else 
    db_set harmony-ap/partyname "$PARTY_NAME"
  fi
  if [[ -z "${SERVER_DN}" ]]; then
    db_input high harmony-ap/serverdn || true
  else 
    db_set harmony-ap/serverdn "$SERVER_DN"
  fi
  if [[ -z "${TOMCAT_PORT}" ]]; then
    db_input high harmony-ap/tomcatport || true
  else 
    db_set harmony-ap/tomcatport "$TOMCAT_PORT"
  fi
  db_endblock
  db_go

  db_beginblock
  if [[ -z "${DB_HOST}" ]]; then
    db_input high harmony-ap/database-host
  else 
    db_set harmony-ap/database-host "$DB_HOST"
  fi
  if [[ -z "${DB_PORT}" ]]; then
    db_input high harmony-ap/database-port
  else 
    db_set harmony-ap/database-port "$DB_PORT"
  fi
  if [[ -z "${DB_SCHEMA}" ]]; then
    db_input high harmony-ap/database-schema
  else 
    db_set harmony-ap/database-schema "$DB_SCHEMA"
  fi
  if [[ -z "${DB_USER}" ]]; then
    db_input high harmony-ap/database-user
  else 
    db_set harmony-ap/database-user "$DB_USER"
  fi
  if [[ -z "${DB_PASS}" ]]; then
    db_input high harmony-ap/database-password
  else 
    db_set harmony-ap/database-password "$DB_PASS"
  fi
  
  db_subst harmony-ap/database-user db_schema "$DB_SCHEMA"
  db_endblock
  db_go

fi

# TODO add some checking of values?

db_stop
