#!/bin/bash

. /usr/share/debconf/confmodule

if [[ "$1" == "remove" ]]; then
  rm -rf /opt/harmony-ap
elif [[ "$1" == "purge" ]]; then
  db_purge
  rm -rf /etc/harmony-ap
elif [[ "$1" == "abort-install" ]]; then
  rm -rf /etc/harmony-ap
  rm -rf /opt/harmony-ap
fi

db_stop

exit 0
