#!/command/with-contenv bash
set -euo pipefail

# shellcheck disable=SC2034 # Used in sourced scripts
readonly STAGE="config-structure"

source /usr/lib/harmony-ap/lib/harmony-common

verify_permissions() {
  local HAS_PERMISSION_ISSUE=0

  [[ -r "$HARMONY_HOME" ]] || {
    log WARN "HARMONY_HOME='$HARMONY_HOME' is not readable"
    HAS_PERMISSION_ISSUE=1
  }

  [[ -w "$HARMONY_BASE" ]] || {
    log WARN "HARMONY_BASE='$HARMONY_BASE' is not writable"
    HAS_PERMISSION_ISSUE=1
  }

  if (( HAS_PERMISSION_ISSUE )); then
    log WARN "Potential file permission issues detected. See documentation:"
    log WARN "  https://github.com/nordic-institute/harmony-common/blob/main/doc/harmony-ap_docker_installation_guide.md#3211-distributed-file-systems#33-file-permissions-and-user-considerations"
  fi
}

create_required_directories() {
  local directories=(
    "$HARMONY_BASE/tomcat"
    "$HARMONY_BASE/cluster"
    "$HARMONY_ADDONS/plugins"
    "$HARMONY_ADDONS/plugins/lib"
    "$HARMONY_ADDONS/extensions"
    "$HARMONY_ADDONS/extensions/lib"
    "$HARMONY_SECURITY"
    "$HARMONY_SECURITY/certs"
    "$HARMONY_CONFIG/policies"
    "$ACTIVEMQ_WORK_DIR"
    "$TOMCAT_WORK_DIR"
    "$TOMCAT_TEMP_DIR"
    "$LOG_DIR"
  )

  local dir
  for dir in "${directories[@]}"; do
    install -d -m 0750 "$dir"
  done
}

create_required_symlinks() {
  local tomcat_conf_link="$HARMONY_BASE/tomcat/conf"

  if [ ! -e "$tomcat_conf_link" ]; then
    ln -s "$HARMONY_CONFIG/tomcat" "$tomcat_conf_link"
    log DEBUG "Created symlink: $tomcat_conf_link to $HARMONY_CONFIG/tomcat"
  fi

  link_directory_defaults "/usr/share/harmony-ap/policies" "${HARMONY_CONFIG}/policies" "default policy"
}

config_structure() {
  log DEBUG "Started"

  verify_permissions
  create_required_directories
  create_required_symlinks

  log DEBUG "Done"
}

config_structure
