#!/command/with-contenv bash
set -euo pipefail

readonly STAGE="init-logback"

source /usr/lib/harmony-ap/lib/harmony-common

: "${LOGBACK_CONFIG_PATH:=${HARMONY_CONFIG}/logback.xml}"

decode_from_base64() {
  log DEBUG "Decoding Logback configuration from Base64 using harmony-base64..."
  harmony-base64 --stage "$STAGE" --input "$LOGBACK_CONFIG_B64" --output "$LOGBACK_CONFIG_PATH" --force
}

init_logback() {
  log DEBUG "Started"

  if [ -n "${LOGBACK_CONFIG_B64:-}" ]; then
    decode_from_base64
  elif [ -f "$LOGBACK_CONFIG_PATH" ]; then
    log DEBUG "Using existing Logback configuration at $LOGBACK_CONFIG_PATH"
  else
    die "Logback configuration not found at '$LOGBACK_CONFIG_PATH'"
  fi

  publish_env LOGBACK_CONFIG_FILE "$LOGBACK_CONFIG_PATH"

  log INFO "Logback configured at: $LOGBACK_CONFIG_PATH"
  log DEBUG "Done"
}

init_logback
