#!/command/with-contenv bash
set -euo pipefail

readonly STAGE="init-logback"

source /usr/lib/harmony-common

readonly LOGBACK_CONFIG_PATH="${LOGBACK_CONFIG_PATH:-$HARMONY_BASE/etc/logback.xml}"

decode_from_base64() {
  log DEBUG "Decoding Logback configuration from Base64 using harmony-base64..."
  harmony-base64 --stage "$STAGE" --input "$LOGBACK_CONFIG_B64" --output "$LOGBACK_CONFIG_PATH" --force
}

use_default_conf() {
  cp --update=none "$HARMONY_HOME/setup/logback.xml" "$LOGBACK_CONFIG_PATH"
  log DEBUG "Using default Logback configuration at $LOGBACK_CONFIG_PATH"
}

init_logback() {
  log DEBUG "Started"

  if [ -n "${LOGBACK_CONFIG_B64:-}" ]; then
    decode_from_base64
  elif [ -f "$LOGBACK_CONFIG_PATH" ]; then
    log DEBUG "Using existing Logback configuration at $LOGBACK_CONFIG_PATH"
  else
    use_default_conf
  fi

  printf "%s" "$LOGBACK_CONFIG_PATH" > /var/run/s6/container_environment/LOGBACK_CONFIG_FILE

  log INFO "Logback configured at: $LOGBACK_CONFIG_PATH"
  log DEBUG "Done"
}

init_logback
