# ===================================================================
#  Access Point (AP)
# ===================================================================
harmony.ap.version=2.6.0
harmony.ap.compile.repo=../harmony-access-point
harmony.ap.compile.maven.profiles=tomcat,default-plugins,database,UI
harmony.ap.compile.artifact.war=Tomcat/Domibus-MSH-tomcat-distribution/target/harmony-MSH-tomcat-distribution-${harmony.ap.version}.war
harmony.ap.compile.artifact.ws-plugin=Plugin-WS/Domibus-default-ws-plugin/target/harmony-default-ws-plugin-${harmony.ap.version}.jar

# ===================================================================
#  Service Metadata Publisher (SMP)
# ===================================================================
harmony.smp.version=2.2.1
harmony.smp.compile.repo=../harmony-smp
harmony.smp.compile.artifact.war=smp-webapp/target/harmonysmp.war

# ===================================================================
#  Third-Party Dependency Configuration
# ===================================================================

# Tomcat
harmony.vendor.tomcat.version=9.0.107
harmony.vendor.tomcat.group=apache
harmony.vendor.tomcat.extension=tar.gz

# Liquibase
harmony.vendor.liquibase.version=4.33.0
harmony.vendor.liquibase.group=liquibase
harmony.vendor.liquibase.extension=tar.gz

# MySQL JDBC Connector
harmony.vendor.mysqlj.version=8.0.33
harmony.vendor.mysqlj.group=com.mysql
harmony.vendor.mysqlj.name=mysql-connector-j

# MariaDB JDBC Connector
harmony.vendor.mariadbj.version=2.7.12
harmony.vendor.mariadbj.group=org.mariadb.jdbc
harmony.vendor.mariadbj.name=mariadb-java-client

# S6-Overlay
harmony.vendor.s6overlay.version=3.2.1.0
harmony.vendor.s6overlay.group=s6-overlay
harmony.vendor.s6overlay.name=s6-overlay
harmony.vendor.s6overlay.extension=tar.xz
harmony.vendor.s6overlay.classifier.noarch=noarch
harmony.vendor.s6overlay.classifier.amd64=x86_64
harmony.vendor.s6overlay.classifier.arm64=aarch64

# ===================================================================
#  Gradle Engine Configuration
# ===================================================================
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true
org.gradle.welcome=never
