input {
  tcp {
    port => 4560
    codec => json
  }
  gelf {
    port => 12201
  }
  file {
    path => "/path/to/another/log.log"
    codec => json
    start_position => "beginning"
    type => "syslog"
    sincedb_path => "/usr/share/logstash/sincedb"
  }
}

filter {
  if [tag] == "harmony-ap" {
    grok {
      match => {
        "message" => "^%{TIMESTAMP_ISO8601:timestamp} \[%{DATA:d_user}\] \[%{DATA:d_domain}\] \[%{DATA:d_messageId}\] \[%{DATA:d_messageEntityId}\] \[%{DATA:thread}\]%{SPACE}%{LOGLEVEL:log_level} %{DATA:logger_class}:%{NUMBER:line_number} - %{GREEDYDATA:log_message}$"
      }
      break_on_match => false
    }
    grok {
      match => {
        "message" => "^%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:log_level} \[%{DATA:thread}\] %{JAVAFILE:logger_class} %{GREEDYDATA:log_message}$"
      }
    }
  } else if [type] == "syslog" {
    grok {
      match => {
        "log" => "%{SYSLOGTIMESTAMP:timestamp} %{SYSLOGHOST:hostname} %{DATA:program}(?:\[%{POSINT:pid}\])?: %{GREEDYDATA:log_message}"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["${ELASTIC_HOSTS}"]
    user => "${ELASTIC_USER}"
    password => "${ELASTIC_PASSWORD}"
    ssl_enabled => true
    ssl_certificate_authorities => "/usr/share/logstash/certs/ca/ca.crt"
  }
}
