-- liquibase formatted sql

-- changeset root:0001:001 contextFilter:legacy
CREATE TABLE SMP_CERTIFICATE (
    ID               BIGINT        NOT NULL COMMENT 'Shared primary key with master table SMP_USER',
    CERTIFICATE_ID   VARCHAR(1024) NULL COMMENT 'Formatted Certificate id using tags: cn, o, c:serialNumber',
    CREATED_ON       DATETIME      NOT NULL,
    CRL_URL          VARCHAR(4000) NULL COMMENT 'URL to the certificate revocation list (CRL)',
    ISSUER           VARCHAR(1024) NULL COMMENT 'Certificate issuer (canonical form)',
    LAST_UPDATED_ON  DATETIME      NOT NULL,
    PEM_ENCODED_CERT LONGTEXT      NULL COMMENT 'PEM encoded  certificate',
    SERIALNUMBER     VARCHAR(128)  NULL COMMENT 'Certificate serial number',
    SUBJECT          VARCHAR(1024) NULL COMMENT 'Certificate subject (canonical form)',
    VALID_FROM       DATETIME      NULL COMMENT 'Certificate valid from date.',
    VALID_TO         DATETIME      NULL COMMENT 'Certificate valid to date.',
    CONSTRAINT PK_SMP_CERTIFICATE PRIMARY KEY (ID),
    UNIQUE (CERTIFICATE_ID)
) COMMENT = 'SMP user certificates';

-- changeset root:0001:002 contextFilter:legacy
CREATE TABLE SMP_CERTIFICATE_AUD (
    ID               BIGINT        NOT NULL,
    REV              BIGINT        NOT NULL,
    REVTYPE          TINYINT(3)    NULL,
    CERTIFICATE_ID   VARCHAR(1024) NULL,
    CREATED_ON       DATETIME      NULL,
    CRL_URL          VARCHAR(4000) NULL,
    ISSUER           VARCHAR(1024) NULL,
    LAST_UPDATED_ON  DATETIME      NULL,
    PEM_ENCODED_CERT LONGTEXT      NULL,
    SERIALNUMBER     VARCHAR(128)  NULL,
    SUBJECT          VARCHAR(1024) NULL,
    VALID_FROM       DATETIME      NULL,
    VALID_TO         DATETIME      NULL,
    CONSTRAINT PK_SMP_CERTIFICATE_AUD PRIMARY KEY (ID, REV)
);

-- changeset root:0001:003 contextFilter:legacy
CREATE TABLE SMP_CONFIGURATION (
    PROPERTY        VARCHAR(512)  NOT NULL COMMENT 'Property name/key',
    CREATED_ON      DATETIME      NOT NULL COMMENT 'Row inserted on date',
    DESCRIPTION     VARCHAR(4000) NULL COMMENT 'Property description',
    LAST_UPDATED_ON DATETIME      NOT NULL COMMENT 'Row modified on date',
    VALUE           VARCHAR(4000) NULL COMMENT 'Property value',
    CONSTRAINT PK_SMP_CONFIGURATION PRIMARY KEY (PROPERTY)
) COMMENT = 'SMP user certificates';

-- changeset root:0001:004 contextFilter:legacy
CREATE TABLE SMP_DOMAIN (
    ID                     BIGINT        NOT NULL COMMENT 'Unique domain id',
    CREATED_ON             DATETIME      NOT NULL,
    DOMAIN_CODE            VARCHAR(256)  NOT NULL COMMENT 'Domain code used as http parameter in rest webservices',
    LAST_UPDATED_ON        DATETIME      NOT NULL,
    SIGNATURE_KEY_ALIAS    VARCHAR(256)  NULL COMMENT 'Signature key alias used for SML integration',
    SML_BLUE_COAT_AUTH     BIT(1)        NOT NULL COMMENT 'Flag for SML authentication type - use CLientCert header or  HTTPS ClientCertificate (key)',
    SML_CLIENT_CERT_HEADER VARCHAR(4000) NULL COMMENT 'Client-Cert header used behind RP - BlueCoat for SML integration',
    SML_CLIENT_KEY_ALIAS   VARCHAR(256)  NULL COMMENT 'Client key alias used for SML integration',
    SML_PARTC_IDENT_REGEXP VARCHAR(4000) NULL COMMENT 'Reqular expresion for participant ids',
    SML_REGISTERED         BIT(1)        NOT NULL COMMENT 'Flag for: Is domain registered in SML',
    SML_SMP_ID             VARCHAR(256)  NULL COMMENT 'SMP ID used for SML integration',
    SML_SUBDOMAIN          VARCHAR(256)  NULL COMMENT 'SML subdomain',
    CONSTRAINT PK_SMP_DOMAIN PRIMARY KEY (ID),
    UNIQUE (DOMAIN_CODE),
    UNIQUE (SML_SUBDOMAIN)
) COMMENT = 'SMP can handle multiple domains. This table contains domain specific data';

-- changeset root:0001:005 contextFilter:legacy
CREATE TABLE SMP_DOMAIN_AUD (
    ID                     BIGINT        NOT NULL,
    REV                    BIGINT        NOT NULL,
    REVTYPE                TINYINT(3)    NULL,
    CREATED_ON             DATETIME      NULL,
    DOMAIN_CODE            VARCHAR(256)  NULL,
    LAST_UPDATED_ON        DATETIME      NULL,
    SIGNATURE_KEY_ALIAS    VARCHAR(256)  NULL,
    SML_BLUE_COAT_AUTH     BIT(1)        NULL,
    SML_CLIENT_CERT_HEADER VARCHAR(4000) NULL,
    SML_CLIENT_KEY_ALIAS   VARCHAR(256)  NULL,
    SML_PARTC_IDENT_REGEXP VARCHAR(4000) NULL,
    SML_REGISTERED         BIT(1)        NULL,
    SML_SMP_ID             VARCHAR(256)  NULL,
    SML_SUBDOMAIN          VARCHAR(256)  NULL,
    CONSTRAINT PK_SMP_DOMAIN_AUD PRIMARY KEY (ID, REV)
);

-- changeset root:0001:006 contextFilter:legacy
CREATE TABLE SMP_DOMAIN_SEQ (
    NEXT_VAL BIGINT NULL
);

-- changeset root:0001:007 contextFilter:legacy
CREATE TABLE SMP_OWNERSHIP (
    FK_SG_ID   BIGINT NOT NULL,
    FK_USER_ID BIGINT NOT NULL,
    CONSTRAINT PK_SMP_OWNERSHIP PRIMARY KEY (FK_SG_ID, FK_USER_ID)
);

-- changeset root:0001:008 contextFilter:legacy
CREATE TABLE SMP_OWNERSHIP_AUD (
    REV        BIGINT     NOT NULL,
    FK_SG_ID   BIGINT     NOT NULL,
    FK_USER_ID BIGINT     NOT NULL,
    REVTYPE    TINYINT(3) NULL,
    CONSTRAINT PK_SMP_OWNERSHIP_AUD PRIMARY KEY (REV, FK_SG_ID, FK_USER_ID)
);

-- changeset root:0001:009 contextFilter:legacy
CREATE TABLE SMP_REVISION_SEQ (
    NEXT_VAL BIGINT NULL
);

-- changeset root:0001:010 contextFilter:legacy
CREATE TABLE SMP_REV_INFO (
    ID            BIGINT       NOT NULL,
    REVISION_DATE DATETIME     NULL,
    TIMESTAMP     BIGINT       NOT NULL,
    USERNAME      VARCHAR(255) NULL,
    CONSTRAINT PK_SMP_REV_INFO PRIMARY KEY (ID)
);

-- changeset root:0001:011 contextFilter:legacy
CREATE TABLE SMP_SERVICE_GROUP (
    ID                     BIGINT       NOT NULL COMMENT 'Unique Servicegroup id',
    CREATED_ON             DATETIME     NOT NULL,
    LAST_UPDATED_ON        DATETIME     NOT NULL,
    PARTICIPANT_IDENTIFIER VARCHAR(256) NOT NULL,
    PARTICIPANT_SCHEME     VARCHAR(256) NOT NULL,
    CONSTRAINT PK_SMP_SERVICE_GROUP PRIMARY KEY (ID)
) COMMENT = 'Service group data - Identifier and scheme';

-- changeset root:0001:012 contextFilter:legacy
CREATE TABLE SMP_SERVICE_GROUP_AUD (
    ID                     BIGINT       NOT NULL,
    REV                    BIGINT       NOT NULL,
    REVTYPE                TINYINT(3)   NULL,
    CREATED_ON             DATETIME     NULL,
    LAST_UPDATED_ON        DATETIME     NULL,
    PARTICIPANT_IDENTIFIER VARCHAR(256) NULL,
    PARTICIPANT_SCHEME     VARCHAR(256) NULL,
    CONSTRAINT PK_SMP_SERVICE_GROUP_AUD PRIMARY KEY (ID, REV)
);

-- changeset root:0001:013 contextFilter:legacy
CREATE TABLE SMP_SERVICE_GROUP_DOMAIN (
    ID              BIGINT   NOT NULL,
    CREATED_ON      DATETIME NOT NULL,
    LAST_UPDATED_ON DATETIME NOT NULL,
    SML_REGISTERED  BIT(1)   NOT NULL,
    FK_DOMAIN_ID    BIGINT   NULL,
    FK_SG_ID        BIGINT   NULL,
    CONSTRAINT PK_SMP_SERVICE_GROUP_DOMAIN PRIMARY KEY (ID)
);

-- changeset root:0001:014 contextFilter:legacy
CREATE TABLE SMP_SERVICE_GROUP_DOMAIN_AUD (
    ID              BIGINT     NOT NULL,
    REV             BIGINT     NOT NULL,
    REVTYPE         TINYINT(3) NULL,
    CREATED_ON      DATETIME   NULL,
    LAST_UPDATED_ON DATETIME   NULL,
    SML_REGISTERED  BIT(1)     NULL,
    FK_DOMAIN_ID    BIGINT     NULL,
    FK_SG_ID        BIGINT     NULL,
    CONSTRAINT PK_SMP_SERVICE_GROUP_DOMAIN_AUD PRIMARY KEY (ID, REV)
);

-- changeset root:0001:015 contextFilter:legacy
CREATE TABLE SMP_SERVICE_GROUP_DOMAIN_SEQ (
    NEXT_VAL BIGINT NULL
);

-- changeset root:0001:016 contextFilter:legacy
CREATE TABLE SMP_SERVICE_GROUP_SEQ (
    NEXT_VAL BIGINT NULL
);

-- changeset root:0001:017 contextFilter:legacy
CREATE TABLE SMP_SERVICE_METADATA (
    ID                  BIGINT       NOT NULL COMMENT 'Shared primary key with master table SMP_SERVICE_METADATA',
    CREATED_ON          DATETIME     NOT NULL,
    DOCUMENT_IDENTIFIER VARCHAR(500) NOT NULL,
    DOCUMENT_SCHEME     VARCHAR(500) NULL,
    LAST_UPDATED_ON     DATETIME     NOT NULL,
    FK_SG_DOM_ID        BIGINT       NOT NULL,
    CONSTRAINT PK_SMP_SERVICE_METADATA PRIMARY KEY (ID)
) COMMENT = 'Service metadata';

-- changeset root:0001:018 contextFilter:legacy
CREATE TABLE SMP_SERVICE_METADATA_AUD (
    ID                  BIGINT       NOT NULL,
    REV                 BIGINT       NOT NULL,
    REVTYPE             TINYINT(3)   NULL,
    CREATED_ON          DATETIME     NULL,
    DOCUMENT_IDENTIFIER VARCHAR(500) NULL,
    DOCUMENT_SCHEME     VARCHAR(500) NULL,
    LAST_UPDATED_ON     DATETIME     NULL,
    FK_SG_DOM_ID        BIGINT       NULL,
    CONSTRAINT PK_SMP_SERVICE_METADATA_AUD PRIMARY KEY (ID, REV)
);

-- changeset root:0001:019 contextFilter:legacy
CREATE TABLE SMP_SERVICE_METADATA_SEQ (
    NEXT_VAL BIGINT NULL
);

-- changeset root:0001:020 contextFilter:legacy
CREATE TABLE SMP_SERVICE_METADATA_XML (
    ID              BIGINT   NOT NULL,
    CREATED_ON      DATETIME NOT NULL,
    LAST_UPDATED_ON DATETIME NOT NULL,
    XML_CONTENT     LONGBLOB NULL COMMENT 'XML service metadata',
    CONSTRAINT PK_SMP_SERVICE_METADATA_XML PRIMARY KEY (ID)
) COMMENT = 'Service group metadata xml blob';

-- changeset root:0001:021 contextFilter:legacy
CREATE TABLE SMP_SERVICE_METADATA_XML_AUD (
    ID              BIGINT     NOT NULL,
    REV             BIGINT     NOT NULL,
    REVTYPE         TINYINT(3) NULL,
    CREATED_ON      DATETIME   NULL,
    LAST_UPDATED_ON DATETIME   NULL,
    XML_CONTENT     LONGBLOB   NULL,
    CONSTRAINT PK_SMP_SERVICE_METADATA_XML_AUD PRIMARY KEY (ID, REV)
);

-- changeset root:0001:022 contextFilter:legacy
CREATE TABLE SMP_SG_EXTENSION (
    ID              BIGINT   NOT NULL,
    CREATED_ON      DATETIME NOT NULL,
    EXTENSION       LONGBLOB NULL COMMENT 'XML extension(s) for servicegroup',
    LAST_UPDATED_ON DATETIME NOT NULL,
    CONSTRAINT PK_SMP_SG_EXTENSION PRIMARY KEY (ID)
) COMMENT = 'Service group extension blob';

-- changeset root:0001:023 contextFilter:legacy
CREATE TABLE SMP_SG_EXTENSION_AUD (
    ID              BIGINT     NOT NULL,
    REV             BIGINT     NOT NULL,
    REVTYPE         TINYINT(3) NULL,
    CREATED_ON      DATETIME   NULL,
    EXTENSION       LONGBLOB   NULL,
    LAST_UPDATED_ON DATETIME   NULL,
    CONSTRAINT PK_SMP_SG_EXTENSION_AUD PRIMARY KEY (ID, REV)
);

-- changeset root:0001:024 contextFilter:legacy
CREATE TABLE SMP_USER (
    ID               BIGINT       NOT NULL COMMENT 'Unique user id',
    ACTIVE           BIT(1)       NOT NULL COMMENT 'Is user active',
    CREATED_ON       DATETIME     NOT NULL,
    EMAIL            VARCHAR(256) NULL COMMENT 'User email',
    LAST_UPDATED_ON  DATETIME     NOT NULL,
    PASSWORD         VARCHAR(256) NULL COMMENT 'BCrypted password for username/password login',
    PASSWORD_CHANGED DATETIME     NULL COMMENT 'Last date when password was changed',
    ROLE             VARCHAR(256) NULL COMMENT 'User role',
    USERNAME         VARCHAR(256) NULL COMMENT 'Login username',
    CONSTRAINT PK_SMP_USER PRIMARY KEY (ID),
    UNIQUE (USERNAME)
) COMMENT = 'SMP can handle multiple domains. This table contains domain specific data';

-- changeset root:0001:025 contextFilter:legacy
CREATE TABLE SMP_USER_AUD (
    ID               BIGINT       NOT NULL,
    REV              BIGINT       NOT NULL,
    REVTYPE          TINYINT(3)   NULL,
    ACTIVE           BIT(1)       NULL,
    CREATED_ON       DATETIME     NULL,
    EMAIL            VARCHAR(256) NULL,
    LAST_UPDATED_ON  DATETIME     NULL,
    PASSWORD         VARCHAR(256) NULL,
    PASSWORD_CHANGED DATETIME     NULL,
    ROLE             VARCHAR(256) NULL,
    USERNAME         VARCHAR(256) NULL,
    CONSTRAINT PK_SMP_USER_AUD PRIMARY KEY (ID, REV)
);

-- changeset root:0001:026 contextFilter:legacy
CREATE TABLE SMP_USER_SEQ (
    NEXT_VAL BIGINT NULL
);

-- changeset root:0001:027 contextFilter:legacy
ALTER TABLE SMP_SERVICE_METADATA
    ADD CONSTRAINT SMP_MT_UNIQ_SG_DOC_IDX UNIQUE (FK_SG_DOM_ID, DOCUMENT_IDENTIFIER, DOCUMENT_SCHEME);

-- changeset root:0001:028 contextFilter:legacy
ALTER TABLE SMP_SERVICE_GROUP
    ADD CONSTRAINT SMP_SG_UNIQ_PARTC_IDX UNIQUE (PARTICIPANT_SCHEME, PARTICIPANT_IDENTIFIER);

-- changeset root:0001:029 contextFilter:legacy
CREATE INDEX FK2786R5MINNKAI3D22B191IIIQ ON SMP_USER_AUD (REV);

-- changeset root:0001:030 contextFilter:legacy
CREATE INDEX FK35QM8XMI74KFENUGEONIJODSG ON SMP_DOMAIN_AUD (REV);

-- changeset root:0001:031 contextFilter:legacy
CREATE INDEX FK6UC9R0EQW16BAOOXTMQJKIH0J ON SMP_SERVICE_GROUP_DOMAIN_AUD (REV);

-- changeset root:0001:032 contextFilter:legacy
CREATE INDEX FKBQR9PDNIK1QXX2HI0XN4N7F61 ON SMP_SERVICE_METADATA_AUD (REV);

-- changeset root:0001:033 contextFilter:legacy
CREATE INDEX FKEVATMLVVWOXFNJXKVMOKKENCB ON SMP_SERVICE_METADATA_XML_AUD (REV);

-- changeset root:0001:034 contextFilter:legacy
CREATE INDEX FKGCVHNK2N34D3C6JHNI5L3S3X3 ON SMP_SERVICE_GROUP_DOMAIN (FK_SG_ID);

-- changeset root:0001:035 contextFilter:legacy
CREATE INDEX FKJ3CAIMHEGWYAV1SCPWRXOSLEF ON SMP_SERVICE_GROUP_AUD (REV);

-- changeset root:0001:036 contextFilter:legacy
CREATE INDEX FKMDO9V2422ADWYEBVL34QA3AP6 ON SMP_SG_EXTENSION_AUD (REV);

-- changeset root:0001:037 contextFilter:legacy
CREATE INDEX FKNRWM8EN8VV10LI8IHWNURWD9E ON SMP_CERTIFICATE_AUD (REV);

-- changeset root:0001:038 contextFilter:legacy
CREATE INDEX FKO186XTEFDA6AVL5P1TUQCHP3N ON SMP_SERVICE_GROUP_DOMAIN (FK_DOMAIN_ID);

-- changeset root:0001:039 contextFilter:legacy
CREATE INDEX FKRNQWQ06LBFWCIUP4RJ8NVJPMY ON SMP_OWNERSHIP (FK_USER_ID);

-- changeset root:0001:040 contextFilter:legacy
CREATE INDEX SMP_SG_PART_ID_IDX ON SMP_SERVICE_GROUP (PARTICIPANT_IDENTIFIER);

-- changeset root:0001:041 contextFilter:legacy
CREATE INDEX SMP_SG_PART_SCH_IDX ON SMP_SERVICE_GROUP (PARTICIPANT_SCHEME);

-- changeset root:0001:042 contextFilter:legacy
CREATE INDEX SMP_SMD_DOC_ID_IDX ON SMP_SERVICE_METADATA (DOCUMENT_IDENTIFIER);

-- changeset root:0001:043 contextFilter:legacy
CREATE INDEX SMP_SMD_DOC_SCH_IDX ON SMP_SERVICE_METADATA (DOCUMENT_SCHEME);

-- changeset root:0001:044 contextFilter:legacy
ALTER TABLE SMP_OWNERSHIP_AUD
    ADD CONSTRAINT FK1LQYNLBK8OW1OUXETF5WYBK3K FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:0001:045 contextFilter:legacy
ALTER TABLE SMP_USER_AUD
    ADD CONSTRAINT FK2786R5MINNKAI3D22B191IIIQ FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:0001:046 contextFilter:legacy
ALTER TABLE SMP_DOMAIN_AUD
    ADD CONSTRAINT FK35QM8XMI74KFENUGEONIJODSG FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:0001:047 contextFilter:legacy
ALTER TABLE SMP_SERVICE_METADATA_XML
    ADD CONSTRAINT FK4B1X06XLAVCGBJNUILGKSI7NM FOREIGN KEY (ID) REFERENCES SMP_SERVICE_METADATA (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:0001:048 contextFilter:legacy
ALTER TABLE SMP_SERVICE_GROUP_DOMAIN_AUD
    ADD CONSTRAINT FK6UC9R0EQW16BAOOXTMQJKIH0J FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:0001:049 contextFilter:legacy
ALTER TABLE SMP_CERTIFICATE
    ADD CONSTRAINT FKAYQGPJ5OT3O8VRPDUUL7SSTTA FOREIGN KEY (ID) REFERENCES SMP_USER (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:0001:050 contextFilter:legacy
ALTER TABLE SMP_SERVICE_METADATA_AUD
    ADD CONSTRAINT FKBQR9PDNIK1QXX2HI0XN4N7F61 FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:0001:051 contextFilter:legacy
ALTER TABLE SMP_SERVICE_METADATA_XML_AUD
    ADD CONSTRAINT FKEVATMLVVWOXFNJXKVMOKKENCB FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:0001:052 contextFilter:legacy
ALTER TABLE SMP_SERVICE_METADATA
    ADD CONSTRAINT FKFVCML6B8X7KN80M30H8PXS7JL FOREIGN KEY (FK_SG_DOM_ID) REFERENCES SMP_SERVICE_GROUP_DOMAIN (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:0001:053 contextFilter:legacy
ALTER TABLE SMP_SERVICE_GROUP_DOMAIN
    ADD CONSTRAINT FKGCVHNK2N34D3C6JHNI5L3S3X3 FOREIGN KEY (FK_SG_ID) REFERENCES SMP_SERVICE_GROUP (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:0001:054 contextFilter:legacy
ALTER TABLE SMP_OWNERSHIP
    ADD CONSTRAINT FKGEXQ5N6FTSID8EHQLJVJH8P4I FOREIGN KEY (FK_SG_ID) REFERENCES SMP_SERVICE_GROUP (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:0001:055 contextFilter:legacy
ALTER TABLE SMP_SERVICE_GROUP_AUD
    ADD CONSTRAINT FKJ3CAIMHEGWYAV1SCPWRXOSLEF FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:0001:056 contextFilter:legacy
ALTER TABLE SMP_SG_EXTENSION_AUD
    ADD CONSTRAINT FKMDO9V2422ADWYEBVL34QA3AP6 FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:0001:057 contextFilter:legacy
ALTER TABLE SMP_CERTIFICATE_AUD
    ADD CONSTRAINT FKNRWM8EN8VV10LI8IHWNURWD9E FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:0001:058 contextFilter:legacy
ALTER TABLE SMP_SERVICE_GROUP_DOMAIN
    ADD CONSTRAINT FKO186XTEFDA6AVL5P1TUQCHP3N FOREIGN KEY (FK_DOMAIN_ID) REFERENCES SMP_DOMAIN (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:0001:059 contextFilter:legacy
ALTER TABLE SMP_OWNERSHIP
    ADD CONSTRAINT FKRNQWQ06LBFWCIUP4RJ8NVJPMY FOREIGN KEY (FK_USER_ID) REFERENCES SMP_USER (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:0001:060 contextFilter:legacy
ALTER TABLE SMP_SG_EXTENSION
    ADD CONSTRAINT FKTF0MFONUGP2JBKQO2O142CHIB FOREIGN KEY (ID) REFERENCES SMP_SERVICE_GROUP (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
