--  *********************************************************************
--  File: migrations/mysql-5.1.0-fix-indexes-recreate.ddl
--  Description: Liquibase SQL script to add generated TYPE_INDEX columns
--               and recreate corrected unique indexes.
--  ChangeSet: 2.0.0-fix-indexes-recreate (db.changelog.xml)
--  Author: harmony
--  Date: 2025-05-27
--  Liquibase version: 4.32.0
--  *********************************************************************

-- 1. TB_D_MESSAGE_PROPERTY
ALTER TABLE `TB_D_MESSAGE_PROPERTY`
    ADD COLUMN `TYPE_INDEX` VARCHAR(255)
        GENERATED ALWAYS AS (COALESCE(`TYPE`, ''))
    STORED;
CREATE UNIQUE INDEX `UIDX_D_MSG_PROP_NAME_VALUE_TYPE`
    ON `TB_D_MESSAGE_PROPERTY` (`NAME`(100), `VALUE`(100), `TYPE_INDEX`(100));

-- 2. TB_D_PART_PROPERTY
ALTER TABLE `TB_D_PART_PROPERTY`
    ADD COLUMN `TYPE_INDEX` VARCHAR(255)
        GENERATED ALWAYS AS (COALESCE(`TYPE`, ''))
    STORED;
CREATE UNIQUE INDEX `UIDX_D_PART_PROP_NAME_VALUE_TYPE`
    ON `TB_D_PART_PROPERTY` (`NAME`(100), `VALUE`(100), `TYPE_INDEX`(100));

-- 3. TB_D_SERVICE
ALTER TABLE `TB_D_SERVICE`
    ADD COLUMN `TYPE_INDEX` VARCHAR(255)
        GENERATED ALWAYS AS (COALESCE(`TYPE`, ''))
    STORED;
CREATE UNIQUE INDEX `UIDX_D_SERVICE_VALUE_TYPE`
    ON `TB_D_SERVICE` (`VALUE`, `TYPE_INDEX`);

-- 4. TB_D_PARTY
ALTER TABLE `TB_D_PARTY`
    ADD COLUMN `TYPE_INDEX` VARCHAR(255)
        GENERATED ALWAYS AS (COALESCE(`TYPE`, ''))
    STORED;
CREATE UNIQUE INDEX `UIDX_D_PARTY_VALUE_TYPE`
    ON `TB_D_PARTY` (`VALUE`, `TYPE_INDEX`);

-- 5. TB_D_AGREEMENT
ALTER TABLE `TB_D_AGREEMENT`
    ADD COLUMN `TYPE_INDEX` VARCHAR(255)
        GENERATED ALWAYS AS (COALESCE(`TYPE`, ''))
    STORED;
CREATE UNIQUE INDEX `UIDX_D_AGREEMENT_VALUE_TYPE`
    ON `TB_D_AGREEMENT` (`VALUE`, `TYPE_INDEX`);