--  *********************************************************************
--  Update Database Script
--  *********************************************************************
--  Change Log: src/main/resources/db/upgrade/5.1.8/changelog-5.1.8-delta.xml
--  Ran at: 7/15/25, 11:01 AM
--  Against: null@offline:mysql?changeLogFile=target/liquibase/changelog-5.1.8-delta.mysql
--  Liquibase version: 4.17.0
--  *********************************************************************

--  Changeset src/main/resources/db/upgrade/5.1.8/../../common/changelog-before-migration-statements-v2.xml::EDELIVERY-12287_assert_previous_migration_succeeded-v2-mysql::Gabriel Maier
-- DELIMITER //

DROP PROCEDURE IF EXISTS EXECUTE_AND_IGNORE_ERROR
//

/*  Call this stored procedure to execute the statement contained in the parameter dmlStatement.
 In case the execution causes an error the statement that failed is rolled back.
 If the MYSQL_ERRNO equals errorNumber then a warning message is logged and the error is ignored otherwise the error is rethrown with the SQLSTATE code 45001 */
CREATE PROCEDURE EXECUTE_AND_IGNORE_ERROR(IN dmlStatement MEDIUMTEXT, IN errorNumber NUMERIC)
    MODIFIES SQL DATA
    SQL SECURITY DEFINER
BEGIN
    DECLARE code NUMERIC DEFAULT -1;
    DECLARE msg TEXT;

    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
        BEGIN
            GET DIAGNOSTICS CONDITION 1
                code = MYSQL_ERRNO, msg = MESSAGE_TEXT;
            IF code = errorNumber THEN
                SELECT CONCAT('Warning: Ignoring error [', code, ': ', msg, '] after executing [', dmlStatement, ']') AS Message;
            ELSE
                SET @error_message = CONCAT('Unhandled exception [', code, ': ', msg, ']') ;
                SIGNAL SQLSTATE '45001'
                    SET MESSAGE_TEXT = @error_message;
            END IF;
        END;

    SET @q = dmlStatement;
    PREPARE stmt FROM @q;
    IF code = -1 THEN
        EXECUTE stmt;
        DEALLOCATE PREPARE stmt;
    END IF;
END
//

--  Changeset src/main/resources/db/upgrade/5.1.8/changelog-5.1.8-delta.xml::EDELIVERY-14339-mysql::tincuse
CALL EXECUTE_AND_IGNORE_ERROR('ALTER TABLE TB_PM_LEG ADD ASYNC_NOTIFICATION BIT(1) NULL', 1060);
//

--  Changeset src/main/resources/db/upgrade/5.1.8/changelog-5.1.8-delta.xml::EDELIVERY-15013::perpeio
UPDATE TB_USER_MESSAGE_LOG
SET PROCESSING_TYPE = 'PULL'
WHERE PROCESSING_TYPE IS NULL
    AND MESSAGE_STATUS_ID_FK IN (
        SELECT ID_PK
        FROM TB_D_MESSAGE_STATUS
        WHERE STATUS IN ('READY_TO_PULL', 'WAITING_FOR_RECEIPT')
    );
//

--  Changeset src/main/resources/db/upgrade/5.1.8/changelog-5.1.8-delta.xml::EDELIVERY-15025::breazio
DROP INDEX IDX_USER_MSG_MESSAGE_ID ON TB_USER_MESSAGE;
//

CREATE INDEX IDX_USER_MSG_MESSAGE_ID ON TB_USER_MESSAGE (MESSAGE_ID);
//

--  Changeset src/main/resources/db/upgrade/5.1.8/changelog-5.1.8-delta.xml::EDELIVERY-14684::nperpion
DROP INDEX IDX_MESSAGE_LOCK_SEARCH ON TB_MESSAGING_LOCK;
//

CREATE INDEX IDX_MESSAGE_LOCK_SEARCH ON TB_MESSAGING_LOCK(INITIATOR, MPC, MESSAGE_STATE, NEXT_ATTEMPT);
//

CREATE INDEX IDX_MESSAGE_LOCK_INIT ON TB_MESSAGING_LOCK(INITIATOR);
//

CREATE INDEX IDX_MESSAGE_LOCK_STATE ON TB_MESSAGING_LOCK(MESSAGE_STATE);
//

--  Changeset src/main/resources/db/upgrade/5.1.8/changelog-5.1.8-delta.xml::EDELIVERY-15206::maierga
-- NEDS-210: add-message-property-index
CALL EXECUTE_AND_IGNORE_ERROR('ALTER TABLE TB_D_MESSAGE_PROPERTY ADD COLUMN CONTENT_HASH VARCHAR(64) GENERATED ALWAYS AS (SHA2(CONCAT(IFNULL(NAME, ''''), ''|'', IFNULL(VALUE, ''''), ''|'', IFNULL(TYPE, '''')), 256)) STORED', 1060);
//

CALL EXECUTE_AND_IGNORE_ERROR('DROP INDEX UIDX_D_MSG_PROP_NAME_VALUE_TYPE ON TB_D_MESSAGE_PROPERTY', 1091);
//

CALL EXECUTE_AND_IGNORE_ERROR('DROP INDEX IDX_D_MSG_PROP_NAME_VALUE_TYPE ON TB_D_MESSAGE_PROPERTY', 1091);
//

CREATE UNIQUE INDEX UIDX_D_MSG_PROP_NAME_VALUE_TYPE ON TB_D_MESSAGE_PROPERTY (CONTENT_HASH);
//

-- CREATE INDEX IDX_D_MSG_PROP_NAME_VALUE_TYPE ON TB_D_MESSAGE_PROPERTY (NAME(100), VALUE(100), (CASE WHEN TYPE IS NULL THEN '' ELSE TYPE END));
CALL EXECUTE_AND_IGNORE_ERROR('ALTER TABLE TB_D_MESSAGE_PROPERTY ADD COLUMN TYPE_NORM VARCHAR(255) GENERATED ALWAYS AS (CASE WHEN TYPE IS NULL THEN '''' ELSE TYPE END) STORED', 1060);
//

CREATE INDEX IDX_D_MSG_PROP_NAME_VALUE_TYPE ON TB_D_MESSAGE_PROPERTY (NAME(100), VALUE(100), TYPE_NORM);
//

-- NEDS-210: add-part-property-index
CALL EXECUTE_AND_IGNORE_ERROR('ALTER TABLE TB_D_PART_PROPERTY ADD COLUMN CONTENT_HASH VARCHAR(64) GENERATED ALWAYS AS (SHA2(CONCAT(IFNULL(NAME, ''''), ''|'', IFNULL(VALUE, ''''), ''|'', IFNULL(TYPE, '''')), 256)) STORED', 1060);
//

CALL EXECUTE_AND_IGNORE_ERROR('DROP INDEX UIDX_D_PART_PROP_NAME_VALUE_TYPE ON TB_D_PART_PROPERTY', 1091);
//

CALL EXECUTE_AND_IGNORE_ERROR('DROP INDEX IDX_D_PART_PROP_NAME_VALUE_TYPE ON TB_D_PART_PROPERTY', 1091);
//

CREATE UNIQUE INDEX UIDX_D_PART_PROP_NAME_VALUE_TYPE ON TB_D_PART_PROPERTY (CONTENT_HASH);
//

-- CREATE INDEX IDX_D_PART_PROP_NAME_VALUE_TYPE ON TB_D_PART_PROPERTY (NAME(100), VALUE(100), (CASE WHEN TYPE IS NULL THEN '' ELSE TYPE END));
CALL EXECUTE_AND_IGNORE_ERROR('ALTER TABLE TB_D_PART_PROPERTY ADD COLUMN TYPE_NORM VARCHAR(255) GENERATED ALWAYS AS (CASE WHEN TYPE IS NULL THEN '''' ELSE TYPE END) STORED', 1060);
//

CREATE INDEX IDX_D_PART_PROP_NAME_VALUE_TYPE ON TB_D_PART_PROPERTY (NAME(100), VALUE(100), TYPE_NORM);
//

-- NEDS-210: add-service-index
CALL EXECUTE_AND_IGNORE_ERROR('ALTER TABLE TB_D_SERVICE ADD COLUMN TYPE_NORM VARCHAR(255) GENERATED ALWAYS AS (CASE WHEN TYPE IS NULL THEN '''' ELSE TYPE END) STORED', 1060);
//

CALL EXECUTE_AND_IGNORE_ERROR('DROP INDEX UIDX_D_SERVICE_VALUE_TYPE ON TB_D_SERVICE', 1091);
//

CREATE UNIQUE INDEX UIDX_D_SERVICE_VALUE_TYPE ON TB_D_SERVICE (VALUE, TYPE_NORM);
//

-- NEDS-210: add-party-index
CALL EXECUTE_AND_IGNORE_ERROR('ALTER TABLE TB_D_PARTY ADD COLUMN TYPE_NORM VARCHAR(255) GENERATED ALWAYS AS (CASE WHEN TYPE IS NULL THEN '''' ELSE TYPE END) STORED', 1060);
//

CALL EXECUTE_AND_IGNORE_ERROR('DROP INDEX UIDX_D_PARTY_VALUE_TYPE ON TB_D_PARTY', 1091);
//

CREATE UNIQUE INDEX UIDX_D_PARTY_VALUE_TYPE ON TB_D_PARTY (VALUE, TYPE_NORM);
//

-- NEDS-210: add-agreement-index
CALL EXECUTE_AND_IGNORE_ERROR('ALTER TABLE TB_D_AGREEMENT ADD COLUMN TYPE_NORM VARCHAR(255) GENERATED ALWAYS AS (CASE WHEN TYPE IS NULL THEN '''' ELSE TYPE END) STORED', 1060);
//

CALL EXECUTE_AND_IGNORE_ERROR('DROP INDEX UIDX_D_AGREEMENT_VALUE_TYPE ON TB_D_AGREEMENT', 1091);
//

CREATE UNIQUE INDEX UIDX_D_AGREEMENT_VALUE_TYPE ON TB_D_AGREEMENT (VALUE, TYPE_NORM);
//

--  Changeset src/main/resources/db/upgrade/5.1.8/../../common/changelog-version-inserts.xml::EDELIVERY-7668-mysql::Catalin Enache
INSERT INTO TB_VERSION (VERSION, BUILD_TIME, CREATION_TIME) VALUES ('5.1.8', '2025-07-15 08:01', (UTC_TIMESTAMP))
    ON DUPLICATE KEY UPDATE BUILD_TIME='2025-07-15 08:01', CREATION_TIME = (UTC_TIMESTAMP);
//
