--  Changeset src/main/resources/db/archive/changelog-4.2.2-delta.xml::EDELIVERY_8033::idragusa
ALTER TABLE TB_USER_MESSAGE_DELETION_JOB RENAME TB_USER_MSG_DELETION_JOB;

DROP INDEX IDX_MESSAGE_LOG_MESSAGE_STATUS ON TB_MESSAGE_LOG;

DROP INDEX IDX_MESSAGE_LOG_MODIFICATION_TIME ON TB_MESSAGE_LOG;

DROP INDEX IDX_MESSAGE_LOG_MESSAGE_TYPE ON TB_MESSAGE_LOG;

CREATE INDEX IDX_MSG_LOG_MESSAGE_STATUS ON TB_MESSAGE_LOG(MESSAGE_STATUS);

CREATE INDEX IDX_MSG_LOG_MODIFICATION_TIME ON TB_MESSAGE_LOG(MODIFICATION_TIME);

CREATE INDEX IDX_MSG_LOG_MESSAGE_TYPE ON TB_MESSAGE_LOG(MESSAGE_TYPE);

