--  Changeset src/main/resources/db/archive/changelog-4.2.1-delta.xml::REMOVE_CASCADE::idragusa
ALTER TABLE TB_PROPERTY DROP FOREIGN KEY FK_2H31P0A2Y6WEG2GRH70C9CYVA;

ALTER TABLE TB_MESSAGING DROP FOREIGN KEY FK_433RGM5A446T59Q6JKB885L3X;

ALTER TABLE TB_MESSAGING DROP FOREIGN KEY FK_53GP9SMTEMQCUIO8O9T10NARM;

ALTER TABLE TB_RECEIPT_DATA DROP FOREIGN KEY FK_8NCCAE214MVS1KH5SGCJ3Y5OY;

ALTER TABLE TB_USER_MESSAGE DROP FOREIGN KEY FK_BE4XC1069QYW2KLHVM3XMG26S;

ALTER TABLE TB_SIGNAL_MESSAGE DROP FOREIGN KEY FK_C08LJJWI4P9DX1RJTCDBE1SFU;

ALTER TABLE TB_PROPERTY DROP FOREIGN KEY FK_CWYLVG6ERNWBA61MO3YAGMKG8;

ALTER TABLE TB_PARTY_ID DROP FOREIGN KEY FK_FKFTD5ORW2ETIU4GHMN3MHX9I;

ALTER TABLE TB_SIGNAL_MESSAGE DROP FOREIGN KEY FK_M6UU2Y6G9BUET3O3K1N4QXWEC;

ALTER TABLE TB_MESSAGE_ACKNW_PROP DROP FOREIGN KEY FK_MSG_ACK_PROP_MSG_ACK;

ALTER TABLE TB_ERROR DROP FOREIGN KEY FK_PRRCMI4GRM4TXHFSFNFHGQ1K1;

ALTER TABLE TB_RAWENVELOPE_LOG DROP FOREIGN KEY FK_SIGNALMSG_ID_FK_RAWENV_ID;

ALTER TABLE TB_PART_INFO DROP FOREIGN KEY FK_TQ6LBN3MP0VSFC6QQU7WXY54G;

ALTER TABLE TB_RAWENVELOPE_LOG DROP FOREIGN KEY FK_USERMSG_ID_FK_RAWENV_ID;

ALTER TABLE TB_PARTY_ID DROP FOREIGN KEY FK_YLUB8LPTGVSCH02MJ71EUUIL;

ALTER TABLE TB_PROPERTY ADD CONSTRAINT FK_2H31P0A2Y6WEG2GRH70C9CYVA FOREIGN KEY (MESSAGEPROPERTIES_ID) REFERENCES TB_USER_MESSAGE (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE TB_MESSAGING ADD CONSTRAINT FK_433RGM5A446T59Q6JKB885L3X FOREIGN KEY (USER_MESSAGE_ID) REFERENCES TB_USER_MESSAGE (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE TB_MESSAGING ADD CONSTRAINT FK_53GP9SMTEMQCUIO8O9T10NARM FOREIGN KEY (SIGNAL_MESSAGE_ID) REFERENCES TB_SIGNAL_MESSAGE (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE TB_RECEIPT_DATA ADD CONSTRAINT FK_8NCCAE214MVS1KH5SGCJ3Y5OY FOREIGN KEY (RECEIPT_ID) REFERENCES TB_RECEIPT (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE TB_USER_MESSAGE ADD CONSTRAINT FK_BE4XC1069QYW2KLHVM3XMG26S FOREIGN KEY (MESSAGEINFO_ID_PK) REFERENCES TB_MESSAGE_INFO (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE TB_SIGNAL_MESSAGE ADD CONSTRAINT FK_C08LJJWI4P9DX1RJTCDBE1SFU FOREIGN KEY (MESSAGEINFO_ID_PK) REFERENCES TB_MESSAGE_INFO (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE TB_PROPERTY ADD CONSTRAINT FK_CWYLVG6ERNWBA61MO3YAGMKG8 FOREIGN KEY (PARTPROPERTIES_ID) REFERENCES TB_PART_INFO (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE TB_PARTY_ID ADD CONSTRAINT FK_FKFTD5ORW2ETIU4GHMN3MHX9I FOREIGN KEY (FROM_ID) REFERENCES TB_USER_MESSAGE (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE TB_SIGNAL_MESSAGE ADD CONSTRAINT FK_M6UU2Y6G9BUET3O3K1N4QXWEC FOREIGN KEY (RECEIPT_ID_PK) REFERENCES TB_RECEIPT (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE TB_MESSAGE_ACKNW_PROP ADD CONSTRAINT FK_MSG_ACK_PROP_MSG_ACK FOREIGN KEY (FK_MSG_ACKNOWLEDGE) REFERENCES TB_MESSAGE_ACKNW (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE TB_ERROR ADD CONSTRAINT FK_PRRCMI4GRM4TXHFSFNFHGQ1K1 FOREIGN KEY (SIGNALMESSAGE_ID) REFERENCES TB_SIGNAL_MESSAGE (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE TB_RAWENVELOPE_LOG ADD CONSTRAINT FK_SIGNALMSG_ID_FK_RAWENV_ID FOREIGN KEY (SIGNALMESSAGE_ID_FK) REFERENCES TB_SIGNAL_MESSAGE (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE TB_PART_INFO ADD CONSTRAINT FK_TQ6LBN3MP0VSFC6QQU7WXY54G FOREIGN KEY (PAYLOADINFO_ID) REFERENCES TB_USER_MESSAGE (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE TB_RAWENVELOPE_LOG ADD CONSTRAINT FK_USERMSG_ID_FK_RAWENV_ID FOREIGN KEY (USERMESSAGE_ID_FK) REFERENCES TB_USER_MESSAGE (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE TB_PARTY_ID ADD CONSTRAINT FK_YLUB8LPTGVSCH02MJ71EUUIL FOREIGN KEY (TO_ID) REFERENCES TB_USER_MESSAGE (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

CREATE INDEX IDX_MESSAGE_LOG_MPC ON TB_MESSAGE_LOG(MPC);

CREATE INDEX IDX_MESSAGE_LOG_DOWNLOADED ON TB_MESSAGE_LOG(DOWNLOADED);

CREATE INDEX IDX_MESSAGE_LOG_MESSAGE_STATUS ON TB_MESSAGE_LOG(MESSAGE_STATUS);

CREATE INDEX IDX_MESSAGE_LOG_MODIFICATION_TIME ON TB_MESSAGE_LOG(MODIFICATION_TIME);

CREATE INDEX IDX_MESSAGE_LOG_MESSAGE_TYPE ON TB_MESSAGE_LOG(MESSAGE_TYPE);

ALTER TABLE TB_PART_INFO MODIFY PART_ORDER INT NULL;

--  Changeset src/main/resources/db/archive/changelog-4.2.1-delta.xml::EDELIVERY-7800::idragusa
CREATE TABLE TB_USER_MESSAGE_DELETION_JOB (ID_PK BIGINT AUTO_INCREMENT NOT NULL, PROCEDURE_NAME VARCHAR(255) NULL COMMENT 'Name of the stored procedure in the database.', MPC VARCHAR(255) NULL, START_RETENTION_DATE timestamp NULL COMMENT 'Expired user messages newer than this date will be deleted by this job', END_RETENTION_DATE timestamp NULL COMMENT 'Expired user messages older than this date will be deleted by this job', MAX_COUNT INT NULL COMMENT 'Maximum number of expired messages to be deleted by one call of the stored procedure', STATE VARCHAR(255) NULL COMMENT 'User message deletion job state: NEW, RUNNING or STOPPED', ACTUAL_START_DATE timestamp NULL COMMENT 'The actual date when this job was started.', CREATION_TIME timestamp DEFAULT NOW() NOT NULL COMMENT 'The date and time when this record was created', CREATED_BY VARCHAR(255) DEFAULT 'DOMIBUS' NOT NULL COMMENT 'The user who created this record', MODIFICATION_TIME timestamp NULL COMMENT 'The date and time when this record was last modified', MODIFIED_BY VARCHAR(255) NULL COMMENT 'The user who last modified this record', CONSTRAINT PK_TB_USER_MESSAGE_DELETION_JOB PRIMARY KEY (ID_PK));

