--  Changeset src/main/resources/db/changelog-5.1-delta.xml::EDELIVERY-10627::Ion Perpegel
ALTER TABLE WS_PLUGIN_TB_BACKEND_MSG_LOG ADD MESSAGE_IDS LONGTEXT NULL;

--  Changeset src/main/resources/db/changelog-5.1-delta.xml::EDELIVERY-9563::Razvan Cretu
CREATE TABLE TB_PARTY_STATUS (ID_PK BIGINT AUTO_INCREMENT NOT NULL, PARTY_NAME VARCHAR(100) NOT NULL, CONNECTIVITY_STATUS VARCHAR(50) NOT NULL, CREATION_TIME timestamp DEFAULT (UTC_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR(255) DEFAULT 'DOMIBUS' NOT NULL, MODIFICATION_TIME timestamp NULL, MODIFIED_BY VARCHAR(255) NULL, CONSTRAINT PK_PARTY_STATUS PRIMARY KEY (ID_PK));

ALTER TABLE TB_PARTY_STATUS ADD CONSTRAINT UK_PARTY_NAME UNIQUE (PARTY_NAME);

--  Changeset src/main/resources/db/changelog-5.1-delta.xml::EDELIVERY-9594_awareness_initial_interval::Razvan Cretu
ALTER TABLE TB_PM_RECEPTION_AWARENESS ADD INITIAL_INTERVAL INT DEFAULT 0 NULL;

--  Changeset src/main/resources/db/changelog-5.1-delta.xml::EDELIVERY-9594_awareness_mult_factor::Razvan Cretu
ALTER TABLE TB_PM_RECEPTION_AWARENESS ADD MULTIPLYING_FACTOR INT DEFAULT 0 NULL;

--  Changeset src/main/resources/db/changelog-5.1-delta.xml::EDELIVERY-7368-1-self-sending::Ion Perpegel
ALTER TABLE TB_USER_MESSAGE DROP KEY UK_USER_MSG_MESSAGE_ID;

DROP INDEX IDX_USER_MSG_MESSAGE_ID ON TB_USER_MESSAGE;

--  Changeset src/main/resources/db/changelog-5.1-delta.xml::EDELIVERY-7368-3-self-sending::Ion Perpegel
ALTER TABLE TB_USER_MESSAGE ADD MSH_ROLE_ID_FK BIGINT NULL;

INSERT IGNORE INTO TB_D_MSH_ROLE
                (ID_PK, ROLE)
            VALUES
                (197001010000000001,'SENDING');

UPDATE TB_USER_MESSAGE t1
            SET t1.MSH_ROLE_ID_FK = (SELECT t2.ID_PK FROM TB_D_MSH_ROLE t2 WHERE t2.ROLE='SENDING')
            WHERE t1.ID_PK = 19700101;

SET @OLD_SQL_SAFE_UPDATES = @@SQL_SAFE_UPDATES;

SET SQL_SAFE_UPDATES = 0;

UPDATE TB_USER_MESSAGE t1
                INNER JOIN TB_USER_MESSAGE_LOG t2 ON t1.ID_PK = t2.ID_PK
                    SET t1.MSH_ROLE_ID_FK = t2.MSH_ROLE_ID_FK;

SET SQL_SAFE_UPDATES = @OLD_SQL_SAFE_UPDATES;

ALTER TABLE TB_USER_MESSAGE MODIFY MSH_ROLE_ID_FK BIGINT NOT NULL;

ALTER TABLE TB_USER_MESSAGE ADD CONSTRAINT FK_USER_MSG_MSH_ROLE FOREIGN KEY (MSH_ROLE_ID_FK) REFERENCES TB_D_MSH_ROLE (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

CREATE INDEX IDX_USER_MSG_MESSAGE_ID ON TB_USER_MESSAGE(MESSAGE_ID, MSH_ROLE_ID_FK);

ALTER TABLE TB_USER_MESSAGE ADD CONSTRAINT UK_USER_MSG_MESSAGE_ID UNIQUE (MESSAGE_ID, MSH_ROLE_ID_FK);

DROP INDEX IDX_SIG_MESS_SIGNAL_MESS_ID ON TB_SIGNAL_MESSAGE;

ALTER TABLE TB_SIGNAL_MESSAGE ADD MSH_ROLE_ID_FK BIGINT NULL;

SET @OLD_SQL_SAFE_UPDATES = @@SQL_SAFE_UPDATES;

SET SQL_SAFE_UPDATES = 0;

UPDATE TB_SIGNAL_MESSAGE t1
                INNER JOIN TB_SIGNAL_MESSAGE_LOG t2 ON t1.ID_PK = t2.ID_PK
                SET t1.MSH_ROLE_ID_FK = t2.MSH_ROLE_ID_FK;

SET SQL_SAFE_UPDATES = @OLD_SQL_SAFE_UPDATES;

CREATE INDEX IDX_SIG_MESS_SIGNAL_MESS_ID ON TB_SIGNAL_MESSAGE(SIGNAL_MESSAGE_ID, MSH_ROLE_ID_FK);

ALTER TABLE TB_SIGNAL_MESSAGE ADD CONSTRAINT UK_SIGNAL_MSG_MESSAGE_ID UNIQUE (SIGNAL_MESSAGE_ID, MSH_ROLE_ID_FK);

ALTER TABLE TB_SIGNAL_MESSAGE MODIFY MSH_ROLE_ID_FK BIGINT NOT NULL;

ALTER TABLE TB_SIGNAL_MESSAGE ADD CONSTRAINT FK_SIGNAL_MSH_ROLE FOREIGN KEY (MSH_ROLE_ID_FK) REFERENCES TB_D_MSH_ROLE (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

--  Changeset src/main/resources/db/changelog-5.1-delta.xml::EDELIVERY-10064-mysql-migration-plans-are-failing::Razvan Cretu
ALTER TABLE WS_PLUGIN_TB_BACKEND_MSG_LOG MODIFY SENT datetime NOT NULL;

ALTER TABLE TB_USER_MESSAGE_LOG MODIFY VERSION INT NOT NULL;

ALTER TABLE TB_ENCRYPTION_KEY MODIFY SECRET_KEY LONGBLOB NOT NULL;

ALTER TABLE TB_ENCRYPTION_KEY MODIFY INIT_VECTOR LONGBLOB NOT NULL;

ALTER TABLE TB_EARCHIVE_BATCH MODIFY REEXPORTED BIT(1) NOT NULL;

ALTER TABLE TB_COMMAND_PROPERTY MODIFY FK_COMMAND BIGINT NOT NULL;

ALTER TABLE TB_COMMAND MODIFY SERVER_NAME VARCHAR(255) NOT NULL;

--  Changeset src/main/resources/db/changelog-5.1-delta.xml::EDELIVERY-10093_metadata_retention::Gabriel Maier
ALTER TABLE TB_PM_MPC ADD RETENTION_METADATA_OFFSET INT DEFAULT 0 NULL;

ALTER TABLE TB_USER_MESSAGE_LOG MODIFY MESSAGE_STATUS_ID_FK BIGINT NOT NULL;

--  Changeset src/main/resources/db/changelog-5.1-delta.xml::EDELIVERY-9686::Lucian Furca
ALTER TABLE TB_PM_SECURITY ADD PROFILE VARCHAR(255) NULL;

--  Changeset src/main/resources/db/changelog-5.1-delta.xml::EDELIVERY-10091::Soumya Chandran 
CREATE TABLE TB_MESSAGES_TO_RESEND (ID_PK BIGINT AUTO_INCREMENT NOT NULL, MESSAGE_ID VARCHAR(255) NOT NULL, CREATION_TIME timestamp DEFAULT (UTC_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR(255) DEFAULT 'DOMIBUS' NOT NULL, MODIFICATION_TIME timestamp NULL, MODIFIED_BY VARCHAR(255) NULL, CONSTRAINT PK_MESSAGES_TO_RESEND PRIMARY KEY (ID_PK));

ALTER TABLE TB_MESSAGES_TO_RESEND ADD CONSTRAINT UK_MESSAGE_ID UNIQUE (MESSAGE_ID);

--  Changeset src/main/resources/db/changelog-5.1-delta.xml::EDELIVERY-10284::Razvan Cretu
ALTER TABLE WS_PLUGIN_TB_BACKEND_MSG_LOG ADD MESSAGE_ENTITY_ID BIGINT NULL;

--  Changeset src/main/resources/db/changelog-5.1-delta.xml::EDELIVERY-10913::Francois Gautier
ALTER TABLE TB_EARCHIVE_BATCH CHANGE ERROR_CODE DOMIBUS_CODE VARCHAR(255);

ALTER TABLE TB_EARCHIVE_BATCH CHANGE ERROR_DETAIL MESSAGE VARCHAR(255);

--  Changeset src/main/resources/db/changelog-5.1-delta.xml::EDELIVERY-10924::idragusa
