--  Changeset src/main/resources/db/archive/5.0/migration/common/changelog-42-50-data-migration-step3.xml::EDELIVERY-7970-drop-indexes-uq-common::Catalin Enache
ALTER TABLE TB_COMMAND_PROPERTY DROP FOREIGN KEY FK_COMMAND_PROPERTY_ID;

ALTER TABLE TB_EVENT_ALERT DROP FOREIGN KEY FK_ALERT_ID;

ALTER TABLE TB_EVENT_ALERT DROP FOREIGN KEY FK_EVENT_ID;

ALTER TABLE TB_EVENT_PROPERTY DROP FOREIGN KEY FK_EVENT_PROPERTY_ID;

ALTER TABLE TB_USER_PASSWORD_HISTORY DROP FOREIGN KEY FK_USER_PASSWORD_HISTORY;

ALTER TABLE TB_USER_ROLES DROP FOREIGN KEY FK_USER_ROLES_ROLE;

ALTER TABLE TB_USER_ROLES DROP FOREIGN KEY FK_USER_ROLES_USER;

ALTER TABLE TB_REV_CHANGES DROP FOREIGN KEY FK_REV_CHANGES_REV_INFO;

ALTER TABLE TB_USER_ROLE_AUD DROP FOREIGN KEY FK_USR_ROL_AUD_REV_INFO;

--  Changeset src/main/resources/db/archive/5.0/migration/common/changelog-42-50-data-migration-step3.xml::EDELIVERY-7970-rename-former-tables-common::Catalin Enache
ALTER TABLE TB_ALERT RENAME OLD_TB_ALERT;

ALTER TABLE TB_EVENT RENAME OLD_TB_EVENT;

ALTER TABLE TB_EVENT_ALERT RENAME OLD_TB_EVENT_ALERT;

ALTER TABLE TB_EVENT_PROPERTY RENAME OLD_TB_EVENT_PROPERTY;

ALTER TABLE TB_COMMAND RENAME OLD_TB_COMMAND;

ALTER TABLE TB_COMMAND_PROPERTY RENAME OLD_TB_COMMAND_PROPERTY;

ALTER TABLE TB_USER RENAME OLD_TB_USER;

ALTER TABLE TB_USER_PASSWORD_HISTORY RENAME OLD_TB_USER_PASSWORD_HISTORY;

ALTER TABLE TB_USER_ROLE RENAME OLD_TB_USER_ROLE;

ALTER TABLE TB_USER_ROLES RENAME OLD_TB_USER_ROLES;

ALTER TABLE TB_REV_INFO RENAME OLD_TB_REV_INFO;

ALTER TABLE TB_USER_ROLES_AUD RENAME OLD_TB_USER_ROLES_AUD;

--  Changeset src/main/resources/db/archive/5.0/migration/common/changelog-42-50-data-migration-step3.xml::EDELIVERY-7970-rename-MIGR-tables-common::Catalin Enache
ALTER TABLE MIGR_TB_ALERT RENAME TB_ALERT;

ALTER TABLE MIGR_TB_EVENT RENAME TB_EVENT;

ALTER TABLE MIGR_TB_EVENT_ALERT RENAME TB_EVENT_ALERT;

ALTER TABLE MIGR_TB_EVENT_PROPERTY RENAME TB_EVENT_PROPERTY;

ALTER TABLE MIGR_TB_COMMAND RENAME TB_COMMAND;

ALTER TABLE MIGR_TB_COMMAND_PROPERTY RENAME TB_COMMAND_PROPERTY;

ALTER TABLE MIGR_TB_USER RENAME TB_USER;

ALTER TABLE MIGR_TB_USER_PASSWORD_HISTORY RENAME TB_USER_PASSWORD_HISTORY;

ALTER TABLE MIGR_TB_USER_ROLE RENAME TB_USER_ROLE;

ALTER TABLE MIGR_TB_USER_ROLES RENAME TB_USER_ROLES;

ALTER TABLE MIGR_TB_REV_INFO RENAME TB_REV_INFO;

ALTER TABLE MIGR_TB_USER_ROLES_AUD RENAME TB_USER_ROLES_AUD;

--  Changeset src/main/resources/db/archive/5.0/migration/common/changelog-42-50-data-migration-step3.xml::EDELIVERY-7970-constraints-common::Catalin Enache
ALTER TABLE TB_COMMAND_PROPERTY ADD CONSTRAINT FK_COMMAND_PROPERTY_ID FOREIGN KEY (FK_COMMAND) REFERENCES TB_COMMAND (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE TB_COMMAND_PROPERTY ADD CONSTRAINT UK_COMMAND_PROP_NAME UNIQUE (FK_COMMAND, PROPERTY_NAME);

ALTER TABLE TB_ALERT ADD CONSTRAINT FK_ALERT_TZ_OFFSET FOREIGN KEY (FK_TIMEZONE_OFFSET) REFERENCES TB_D_TIMEZONE_OFFSET (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

CREATE INDEX IDX_ALERT_TZ_OFFSET ON TB_ALERT(FK_TIMEZONE_OFFSET);

CREATE INDEX IDX_ALERT_STATUS ON TB_ALERT(ALERT_STATUS);

ALTER TABLE TB_EVENT_ALERT ADD CONSTRAINT FK_ALERT_ID FOREIGN KEY (FK_ALERT) REFERENCES TB_ALERT (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE TB_EVENT_ALERT ADD CONSTRAINT FK_EVENT_ID FOREIGN KEY (FK_EVENT) REFERENCES TB_EVENT (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

CREATE INDEX IDX_FK_ALERT ON TB_EVENT_ALERT(FK_ALERT);

ALTER TABLE TB_EVENT_PROPERTY ADD CONSTRAINT FK_EVENT_PROPERTY_ID FOREIGN KEY (FK_EVENT) REFERENCES TB_EVENT (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

CREATE INDEX IDX_FK_EVENT_PROPERTY ON TB_EVENT_PROPERTY(FK_EVENT);

ALTER TABLE TB_USER ADD CONSTRAINT UK_USER_NAME UNIQUE (USER_NAME);

ALTER TABLE TB_USER_PASSWORD_HISTORY ADD CONSTRAINT FK_USER_PASSWORD_HISTORY FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

CREATE INDEX IDX_UPH_USER_ID ON TB_USER_PASSWORD_HISTORY(USER_ID);

ALTER TABLE TB_USER_ROLE ADD CONSTRAINT UK_ROLE_NAME UNIQUE (ROLE_NAME);

ALTER TABLE TB_USER_ROLES ADD CONSTRAINT FK_USER_ROLES_ROLE FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE TB_USER_ROLES ADD CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (ROLE_ID) REFERENCES TB_USER_ROLE (ID_PK) ON UPDATE RESTRICT ON DELETE RESTRICT;

CREATE INDEX IDX_ROLE_ID ON TB_USER_ROLES(ROLE_ID);

--  Changeset src/main/resources/db/archive/5.0/migration/common/changelog-42-50-data-migration-step3.xml::EDELIVERY-7833-oracle-sequence-common::Catalin Enache
--  Changeset src/main/resources/db/archive/5.0/migration/multitenancy/changelog-42-50-data-migration-step3.xml::EDELIVERY-7970-rename-former-tables-multitenancy::Catalin Enache
ALTER TABLE TB_USER_DOMAIN RENAME OLD_TB_USER_DOMAIN;

ALTER TABLE TB_REV_CHANGES RENAME OLD_TB_REV_CHANGES;

ALTER TABLE TB_USER_AUD RENAME OLD_TB_USER_AUD;

ALTER TABLE TB_USER_ROLE_AUD RENAME OLD_TB_USER_ROLE_AUD;

--  Changeset src/main/resources/db/archive/5.0/migration/multitenancy/changelog-42-50-data-migration-step3.xml::EDELIVERY-7970-rename-MIGR-tables-multitenancy::Catalin Enache
ALTER TABLE MIGR_TB_USER_DOMAIN RENAME TB_USER_DOMAIN;

ALTER TABLE MIGR_TB_REV_CHANGES RENAME TB_REV_CHANGES;

ALTER TABLE MIGR_TB_USER_AUD RENAME TB_USER_AUD;

ALTER TABLE MIGR_TB_USER_ROLE_AUD RENAME TB_USER_ROLE_AUD;

--  Changeset src/main/resources/db/archive/5.0/migration/multitenancy/changelog-42-50-data-migration-step3.xml::EDELIVERY-7970-constraints-multitenancy::Catalin Enache
ALTER TABLE TB_USER_DOMAIN ADD CONSTRAINT UK_DOMAIN_USER_NAME UNIQUE (USER_NAME);

ALTER TABLE TB_REV_CHANGES ADD CONSTRAINT FK_REV_CHANGES_REV_INFO FOREIGN KEY (REV) REFERENCES TB_REV_INFO (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

CREATE INDEX IDX_FK_REV_CHANGES_REV_INFO ON TB_REV_CHANGES(REV);

ALTER TABLE TB_USER_AUD ADD CONSTRAINT FK_USER_AUD_REV FOREIGN KEY (REV) REFERENCES TB_REV_INFO (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

CREATE INDEX IDX_FK_USER_AUD_REV ON TB_USER_AUD(REV);

ALTER TABLE TB_USER_ROLE_AUD ADD CONSTRAINT FK_USR_ROL_AUD_REV_INFO FOREIGN KEY (REV) REFERENCES TB_REV_INFO (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

CREATE INDEX IDX_FK_USR_ROL_AUD_REV_INFO ON TB_USER_ROLE_AUD(REV);

--  Changeset src/main/resources/db/archive/5.0/migration/multitenancy/changelog-42-50-data-migration-step3.xml::EDELIVERY-9028-Audit Table for TB_USER_DOMAIN::Ion Perpegel
CREATE INDEX IDX_FK_USR_DOM_AUD_REV_INFO ON TB_USER_DOMAIN_AUD(REV);

ALTER TABLE TB_USER_DOMAIN_AUD ADD CONSTRAINT FK_USR_DOM_AUD_REV_INFO FOREIGN KEY (REV) REFERENCES TB_REV_INFO (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

