DELIMITER //

DROP PROCEDURE IF EXISTS MIGRATE_42_TO_50_utc_conversion
//

CREATE PROCEDURE MIGRATE_42_TO_50_utc_conversion(IN TIMEZONE VARCHAR(255))
BEGIN
    UPDATE TB_ACTION_AUDIT
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_ACTION_AUDIT
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_ACTION_AUDIT
    SET REVISION_DATE = CONVERT_TZ(REVISION_DATE, TIMEZONE, 'UTC')
    WHERE REVISION_DATE IS NOT NULL;

    UPDATE TB_ALERT
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_ALERT
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_ALERT
    SET NEXT_ATTEMPT = CONVERT_TZ(NEXT_ATTEMPT, TIMEZONE, 'UTC')
    WHERE NEXT_ATTEMPT IS NOT NULL;

    UPDATE TB_ALERT
    SET PROCESSED_TIME = CONVERT_TZ(PROCESSED_TIME, TIMEZONE, 'UTC')
    WHERE PROCESSED_TIME IS NOT NULL;

    UPDATE TB_ALERT
    SET REPORTING_TIME = CONVERT_TZ(REPORTING_TIME, TIMEZONE, 'UTC')
    WHERE REPORTING_TIME IS NOT NULL;

    UPDATE TB_ALERT
    SET REPORTING_TIME_FAILURE = CONVERT_TZ(REPORTING_TIME_FAILURE, TIMEZONE, 'UTC')
    WHERE REPORTING_TIME_FAILURE IS NOT NULL;

    UPDATE TB_AUTHENTICATION_ENTRY
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_AUTHENTICATION_ENTRY
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_AUTHENTICATION_ENTRY
    SET PASSWORD_CHANGE_DATE = CONVERT_TZ(PASSWORD_CHANGE_DATE, TIMEZONE, 'UTC')
    WHERE PASSWORD_CHANGE_DATE IS NOT NULL;

    UPDATE TB_AUTHENTICATION_ENTRY
    SET SUSPENSION_DATE = CONVERT_TZ(SUSPENSION_DATE, TIMEZONE, 'UTC')
    WHERE SUSPENSION_DATE IS NOT NULL;

    UPDATE TB_AUTHENTICATION_ENTRY_AUD
    SET PASSWORD_CHANGE_DATE = CONVERT_TZ(PASSWORD_CHANGE_DATE, TIMEZONE, 'UTC')
    WHERE PASSWORD_CHANGE_DATE IS NOT NULL;

    UPDATE TB_BACKEND_FILTER
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_BACKEND_FILTER
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_CERTIFICATE
    SET ALERT_EXP_NOTIFICATION_DATE = CONVERT_TZ(ALERT_EXP_NOTIFICATION_DATE, TIMEZONE, 'UTC')
    WHERE ALERT_EXP_NOTIFICATION_DATE IS NOT NULL;

    UPDATE TB_CERTIFICATE
    SET ALERT_IMM_NOTIFICATION_DATE = CONVERT_TZ(ALERT_IMM_NOTIFICATION_DATE, TIMEZONE, 'UTC')
    WHERE ALERT_IMM_NOTIFICATION_DATE IS NOT NULL;

    UPDATE TB_CERTIFICATE
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_CERTIFICATE
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_CERTIFICATE
    SET REVOKE_NOTIFICATION_DATE = CONVERT_TZ(REVOKE_NOTIFICATION_DATE, TIMEZONE, 'UTC')
    WHERE REVOKE_NOTIFICATION_DATE IS NOT NULL;

    UPDATE TB_CERTIFICATE
    SET NOT_VALID_BEFORE_DATE = CONVERT_TZ(NOT_VALID_BEFORE_DATE, TIMEZONE, 'UTC')
    WHERE NOT_VALID_BEFORE_DATE IS NOT NULL;

    UPDATE TB_CERTIFICATE
    SET NOT_VALID_AFTER_DATE = CONVERT_TZ(NOT_VALID_AFTER_DATE, TIMEZONE, 'UTC')
    WHERE NOT_VALID_AFTER_DATE IS NOT NULL;

    UPDATE TB_CERTIFICATE_AUD
    SET ALERT_EXP_NOTIFICATION_DATE = CONVERT_TZ(ALERT_EXP_NOTIFICATION_DATE, TIMEZONE, 'UTC')
    WHERE ALERT_EXP_NOTIFICATION_DATE IS NOT NULL;

    UPDATE TB_CERTIFICATE_AUD
    SET ALERT_IMM_NOTIFICATION_DATE = CONVERT_TZ(ALERT_IMM_NOTIFICATION_DATE, TIMEZONE, 'UTC')
    WHERE ALERT_IMM_NOTIFICATION_DATE IS NOT NULL;

    UPDATE TB_CERTIFICATE_AUD
    SET REVOKE_NOTIFICATION_DATE = CONVERT_TZ(REVOKE_NOTIFICATION_DATE, TIMEZONE, 'UTC')
    WHERE REVOKE_NOTIFICATION_DATE IS NOT NULL;

    UPDATE TB_CERTIFICATE_AUD
    SET NOT_VALID_BEFORE_DATE = CONVERT_TZ(NOT_VALID_BEFORE_DATE, TIMEZONE, 'UTC')
    WHERE NOT_VALID_BEFORE_DATE IS NOT NULL;

    UPDATE TB_CERTIFICATE_AUD
    SET NOT_VALID_AFTER_DATE = CONVERT_TZ(NOT_VALID_AFTER_DATE, TIMEZONE, 'UTC')
    WHERE NOT_VALID_AFTER_DATE IS NOT NULL;

    UPDATE TB_COMMAND
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_COMMAND
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_COMMAND_PROPERTY
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_COMMAND_PROPERTY
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_ENCRYPTION_KEY
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_ENCRYPTION_KEY
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_ERROR
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_ERROR
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_ERROR_LOG
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_ERROR_LOG
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_ERROR_LOG
    SET NOTIFIED = CONVERT_TZ(NOTIFIED, TIMEZONE, 'UTC')
    WHERE NOTIFIED IS NOT NULL;

    UPDATE TB_ERROR_LOG
    SET TIME_STAMP = CONVERT_TZ(TIME_STAMP, TIMEZONE, 'UTC')
    WHERE TIME_STAMP IS NOT NULL;

    UPDATE TB_EVENT
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_EVENT
    SET LAST_ALERT_DATE = CONVERT_TZ(LAST_ALERT_DATE, TIMEZONE, 'UTC')
    WHERE LAST_ALERT_DATE IS NOT NULL;

    UPDATE TB_EVENT
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_EVENT
    SET REPORTING_TIME = CONVERT_TZ(REPORTING_TIME, TIMEZONE, 'UTC')
    WHERE REPORTING_TIME IS NOT NULL;

    UPDATE TB_EVENT_ALERT
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_EVENT_ALERT
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_EVENT_PROPERTY
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_EVENT_PROPERTY
    SET DATE_VALUE = CONVERT_TZ(DATE_VALUE, TIMEZONE, 'UTC')
    WHERE DATE_VALUE IS NOT NULL;

    UPDATE TB_EVENT_PROPERTY
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGE_ACKNW
    SET ACKNOWLEDGE_DATE = CONVERT_TZ(ACKNOWLEDGE_DATE, TIMEZONE, 'UTC')
    WHERE ACKNOWLEDGE_DATE IS NOT NULL;

    UPDATE TB_MESSAGE_ACKNW
    SET CREATE_DATE = CONVERT_TZ(CREATE_DATE, TIMEZONE, 'UTC')
    WHERE CREATE_DATE IS NOT NULL;

    UPDATE TB_MESSAGE_ACKNW
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGE_ACKNW
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGE_ACKNW_PROP
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGE_ACKNW_PROP
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PROPERTY
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PROPERTY
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGING
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGING
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGING_LOCK
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGING_LOCK
    SET MESSAGE_RECEIVED = CONVERT_TZ(MESSAGE_RECEIVED, TIMEZONE, 'UTC')
    WHERE MESSAGE_RECEIVED IS NOT NULL;

    UPDATE TB_MESSAGING_LOCK
    SET MESSAGE_STALED = CONVERT_TZ(MESSAGE_STALED, TIMEZONE, 'UTC')
    WHERE MESSAGE_STALED IS NOT NULL;

    UPDATE TB_MESSAGING_LOCK
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGING_LOCK
    SET NEXT_ATTEMPT = CONVERT_TZ(NEXT_ATTEMPT, TIMEZONE, 'UTC')
    WHERE NEXT_ATTEMPT IS NOT NULL;

    UPDATE TB_PART_INFO
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PART_INFO
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PARTY_ID
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PARTY_ID
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PLUGIN_USER_PASSWD_HISTORY
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PLUGIN_USER_PASSWD_HISTORY
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PLUGIN_USER_PASSWD_HISTORY
    SET PASSWORD_CHANGE_DATE = CONVERT_TZ(PASSWORD_CHANGE_DATE, TIMEZONE, 'UTC')
    WHERE PASSWORD_CHANGE_DATE IS NOT NULL;

    UPDATE TB_PM_ACTION
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_ACTION
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_AGREEMENT
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_AGREEMENT
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_BUSINESS_PROCESS
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_BUSINESS_PROCESS
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_CONFIGURATION
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_CONFIGURATION
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_CONFIGURATION_RAW
    SET CONFIGURATION_DATE = CONVERT_TZ(CONFIGURATION_DATE, TIMEZONE, 'UTC')
    WHERE CONFIGURATION_DATE IS NOT NULL;

    UPDATE TB_PM_CONFIGURATION_RAW
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_CONFIGURATION_RAW
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_CONFIGURATION_RAW_AUD
    SET CONFIGURATION_DATE = CONVERT_TZ(CONFIGURATION_DATE, TIMEZONE, 'UTC')
    WHERE CONFIGURATION_DATE IS NOT NULL;

    UPDATE TB_PM_ERROR_HANDLING
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_ERROR_HANDLING
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_JOIN_PAYLOAD_PROFILE
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_JOIN_PAYLOAD_PROFILE
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_JOIN_PROCESS_INIT_PARTY
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_JOIN_PROCESS_INIT_PARTY
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_JOIN_PROCESS_LEG
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_JOIN_PROCESS_LEG
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_JOIN_PROCESS_RESP_PARTY
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_JOIN_PROCESS_RESP_PARTY
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_JOIN_PROPERTY_SET
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_JOIN_PROPERTY_SET
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_LEG
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_LEG
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_LEG_MPC
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_LEG_MPC
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_MEP
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_MEP
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_MEP_BINDING
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_MEP_BINDING
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_MESSAGE_PROPERTY
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_MESSAGE_PROPERTY
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_MESSAGE_PROPERTY_SET
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_MESSAGE_PROPERTY_SET
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_MPC
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_MPC
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_PARTY
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_PARTY
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_PARTY_ID_TYPE
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_PARTY_ID_TYPE
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_PARTY_IDENTIFIER
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_PARTY_IDENTIFIER
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_PAYLOAD
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_PAYLOAD
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_PAYLOAD_PROFILE
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_PAYLOAD_PROFILE
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_PROCESS
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_PROCESS
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_RECEPTION_AWARENESS
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_RECEPTION_AWARENESS
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_RELIABILITY
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_RELIABILITY
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_ROLE
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_ROLE
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_SECURITY
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_SECURITY
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_SERVICE
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_SERVICE
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_PM_SPLITTING
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_PM_SPLITTING
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_RECEIPT
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_RECEIPT
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_RECEIPT_DATA
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_RECEIPT_DATA
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_REV_CHANGES
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_REV_CHANGES
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_REV_INFO
    SET REVISION_DATE = CONVERT_TZ(REVISION_DATE, TIMEZONE, 'UTC')
    WHERE REVISION_DATE IS NOT NULL;

    UPDATE TB_ROUTING_CRITERIA
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_ROUTING_CRITERIA
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_SEND_ATTEMPT
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_SEND_ATTEMPT
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_SEND_ATTEMPT
    SET START_DATE = CONVERT_TZ(START_DATE, TIMEZONE, 'UTC')
    WHERE START_DATE IS NOT NULL;

    UPDATE TB_SEND_ATTEMPT
    SET END_DATE = CONVERT_TZ(END_DATE, TIMEZONE, 'UTC')
    WHERE END_DATE IS NOT NULL;

    UPDATE TB_MESSAGE_FRAGMENT
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGE_FRAGMENT
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGE_GROUP
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGE_GROUP
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGE_HEADER
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGE_HEADER
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_USER
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_USER
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_USER
    SET PASSWORD_CHANGE_DATE = CONVERT_TZ(PASSWORD_CHANGE_DATE, TIMEZONE, 'UTC')
    WHERE PASSWORD_CHANGE_DATE IS NOT NULL;

    UPDATE TB_USER
    SET SUSPENSION_DATE = CONVERT_TZ(SUSPENSION_DATE, TIMEZONE, 'UTC')
    WHERE SUSPENSION_DATE IS NOT NULL;

    UPDATE TB_USER_AUD
    SET PASSWORD_CHANGE_DATE = CONVERT_TZ(PASSWORD_CHANGE_DATE, TIMEZONE, 'UTC')
    WHERE PASSWORD_CHANGE_DATE IS NOT NULL;

    UPDATE TB_USER_MESSAGE
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_USER_MESSAGE
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_SIGNAL_MESSAGE
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_SIGNAL_MESSAGE
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGE_LOG
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGE_LOG
    SET DELETED = CONVERT_TZ(DELETED, TIMEZONE, 'UTC')
    WHERE DELETED IS NOT NULL;

    UPDATE TB_MESSAGE_LOG
    SET DOWNLOADED = CONVERT_TZ(DOWNLOADED, TIMEZONE, 'UTC')
    WHERE DOWNLOADED IS NOT NULL;

    UPDATE TB_MESSAGE_LOG
    SET FAILED = CONVERT_TZ(FAILED, TIMEZONE, 'UTC')
    WHERE FAILED IS NOT NULL;

    UPDATE TB_MESSAGE_LOG
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGE_LOG
    SET NEXT_ATTEMPT = CONVERT_TZ(NEXT_ATTEMPT, TIMEZONE, 'UTC')
    WHERE NEXT_ATTEMPT IS NOT NULL;

    UPDATE TB_MESSAGE_LOG
    SET RECEIVED = CONVERT_TZ(RECEIVED, TIMEZONE, 'UTC')
    WHERE RECEIVED IS NOT NULL;

    UPDATE TB_MESSAGE_LOG
    SET RESTORED = CONVERT_TZ(RESTORED, TIMEZONE, 'UTC')
    WHERE RESTORED IS NOT NULL;

    UPDATE TB_MESSAGE_INFO
    SET TIME_STAMP = CONVERT_TZ(TIME_STAMP, TIMEZONE, 'UTC')
    WHERE TIME_STAMP IS NOT NULL;

    UPDATE TB_MESSAGE_INFO
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_MESSAGE_INFO
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_RAWENVELOPE_LOG
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_RAWENVELOPE_LOG
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_USER_PASSWORD_HISTORY
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_USER_PASSWORD_HISTORY
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_USER_PASSWORD_HISTORY
    SET PASSWORD_CHANGE_DATE = CONVERT_TZ(PASSWORD_CHANGE_DATE, TIMEZONE, 'UTC')
    WHERE PASSWORD_CHANGE_DATE IS NOT NULL;

    UPDATE TB_USER_ROLE
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_USER_ROLE
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_USER_ROLES
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_USER_ROLES
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE WS_PLUGIN_TB_MESSAGE_LOG
    SET RECEIVED = CONVERT_TZ(RECEIVED, TIMEZONE, 'UTC')
    WHERE RECEIVED IS NOT NULL;

    COMMIT;
END
//

DROP PROCEDURE IF EXISTS MIGRATE_42_TO_50_utc_conversion_multitenancy
//

CREATE PROCEDURE MIGRATE_42_TO_50_utc_conversion_multitenancy(IN TIMEZONE VARCHAR(255))
BEGIN
    UPDATE TB_ALERT
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_ALERT
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_ALERT
    SET NEXT_ATTEMPT = CONVERT_TZ(NEXT_ATTEMPT, TIMEZONE, 'UTC')
    WHERE NEXT_ATTEMPT IS NOT NULL;

    UPDATE TB_ALERT
    SET PROCESSED_TIME = CONVERT_TZ(PROCESSED_TIME, TIMEZONE, 'UTC')
    WHERE PROCESSED_TIME IS NOT NULL;

    UPDATE TB_ALERT
    SET REPORTING_TIME = CONVERT_TZ(REPORTING_TIME, TIMEZONE, 'UTC')
    WHERE REPORTING_TIME IS NOT NULL;

    UPDATE TB_ALERT
    SET REPORTING_TIME_FAILURE = CONVERT_TZ(REPORTING_TIME_FAILURE, TIMEZONE, 'UTC')
    WHERE REPORTING_TIME_FAILURE IS NOT NULL;

    UPDATE TB_COMMAND
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_COMMAND
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_COMMAND_PROPERTY
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_COMMAND_PROPERTY
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_EVENT
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_EVENT
    SET LAST_ALERT_DATE = CONVERT_TZ(LAST_ALERT_DATE, TIMEZONE, 'UTC')
    WHERE LAST_ALERT_DATE IS NOT NULL;

    UPDATE TB_EVENT
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_EVENT
    SET REPORTING_TIME = CONVERT_TZ(REPORTING_TIME, TIMEZONE, 'UTC')
    WHERE REPORTING_TIME IS NOT NULL;

    UPDATE TB_EVENT_ALERT
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_EVENT_ALERT
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_EVENT_PROPERTY
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_EVENT_PROPERTY
    SET DATE_VALUE = CONVERT_TZ(DATE_VALUE, TIMEZONE, 'UTC')
    WHERE DATE_VALUE IS NOT NULL;

    UPDATE TB_EVENT_PROPERTY
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_REV_CHANGES
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_REV_CHANGES
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_REV_INFO
    SET REVISION_DATE = CONVERT_TZ(REVISION_DATE, TIMEZONE, 'UTC')
    WHERE REVISION_DATE IS NOT NULL;

    UPDATE TB_USER
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_USER
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_USER
    SET PASSWORD_CHANGE_DATE = CONVERT_TZ(PASSWORD_CHANGE_DATE, TIMEZONE, 'UTC')
    WHERE PASSWORD_CHANGE_DATE IS NOT NULL;

    UPDATE TB_USER
    SET SUSPENSION_DATE = CONVERT_TZ(SUSPENSION_DATE, TIMEZONE, 'UTC')
    WHERE SUSPENSION_DATE IS NOT NULL;

    UPDATE TB_USER_AUD
    SET PASSWORD_CHANGE_DATE = CONVERT_TZ(PASSWORD_CHANGE_DATE, TIMEZONE, 'UTC')
    WHERE PASSWORD_CHANGE_DATE IS NOT NULL;

    UPDATE TB_USER_DOMAIN
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_USER_DOMAIN
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_USER_PASSWORD_HISTORY
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_USER_PASSWORD_HISTORY
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_USER_PASSWORD_HISTORY
    SET PASSWORD_CHANGE_DATE = CONVERT_TZ(PASSWORD_CHANGE_DATE, TIMEZONE, 'UTC')
    WHERE PASSWORD_CHANGE_DATE IS NOT NULL;

    UPDATE TB_USER_ROLE
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_USER_ROLE
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    UPDATE TB_USER_ROLES
    SET CREATION_TIME = CONVERT_TZ(CREATION_TIME, TIMEZONE, 'UTC')
    WHERE CREATION_TIME IS NOT NULL;

    UPDATE TB_USER_ROLES
    SET MODIFICATION_TIME = CONVERT_TZ(MODIFICATION_TIME, TIMEZONE, 'UTC')
    WHERE MODIFICATION_TIME IS NOT NULL;

    COMMIT;
END
//

--  Changeset src/main/resources/db/archive/5.0/migration/common/changelog-42-50-data-migration-step1.xml::EDELIVERY-7970-prepare-common::Catalin Enache
--  drop previously created tables for migration - MIGR_* and TB_D tables
DROP TABLE IF EXISTS MIGR_TB_ALERT
//

DROP TABLE IF EXISTS MIGR_TB_EVENT
//

DROP TABLE IF EXISTS MIGR_TB_EVENT_ALERT
//

DROP TABLE IF EXISTS MIGR_TB_EVENT_PROPERTY
//

DROP TABLE IF EXISTS MIGR_TB_COMMAND
//

DROP TABLE IF EXISTS MIGR_TB_COMMAND_PROPERTY
//

DROP TABLE IF EXISTS MIGR_TB_USER
//

DROP TABLE IF EXISTS MIGR_TB_USER_PASSWORD_HISTORY
//

DROP TABLE IF EXISTS MIGR_TB_USER_ROLE
//

DROP TABLE IF EXISTS MIGR_TB_USER_ROLES
//

DROP TABLE IF EXISTS MIGR_TB_REV_INFO
//

DROP TABLE IF EXISTS MIGR_TB_REV_CHANGES
//

DROP TABLE IF EXISTS MIGR_TB_USER_AUD
//

DROP TABLE IF EXISTS MIGR_TB_USER_ROLE_AUD
//

DROP TABLE IF EXISTS MIGR_TB_USER_ROLES_AUD
//

--  Changeset src/main/resources/db/archive/5.0/migration/common/changelog-42-50-data-migration-step1.xml::EDELIVERY-7970-recreate-dictionary-tables-common::Catalin Enache
CREATE TABLE TB_D_TIMEZONE_OFFSET (ID_PK BIGINT AUTO_INCREMENT NOT NULL, NEXT_ATTEMPT_TIMEZONE_ID VARCHAR(255) NULL COMMENT 'Time zone ID on the application server to use when converting the next attempt for displaying it to the user', NEXT_ATTEMPT_OFFSET_SECONDS INT NULL COMMENT 'Offset in seconds of the time zone on the application server to use when converting the next attempt for displaying it to the user', CREATION_TIME timestamp DEFAULT (UTC_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR(255) DEFAULT 'DOMIBUS' NOT NULL, MODIFICATION_TIME timestamp NULL, MODIFIED_BY VARCHAR(255) NULL, CONSTRAINT PK_D_TIMEZONE_OFFSET PRIMARY KEY (ID_PK));

ALTER TABLE TB_D_TIMEZONE_OFFSET ADD CONSTRAINT UK_D_TIMEZONE_OFFSET UNIQUE (NEXT_ATTEMPT_TIMEZONE_ID, NEXT_ATTEMPT_OFFSET_SECONDS);

--  Changeset src/main/resources/db/archive/5.0/migration/common/changelog-42-50-data-migration-step1.xml::EDELIVERY-8441-recreate-MIGR-tables-for-primary-key-migration-common::Sebastian-Ion TINCU
CREATE TABLE MIGR_TB_REV_INFO (ID BIGINT AUTO_INCREMENT NOT NULL, TIMESTAMP BIGINT NULL, REVISION_DATE timestamp NULL, USER_NAME VARCHAR(255) NULL, CONSTRAINT PK_REV_INFO PRIMARY KEY (ID));

CREATE TABLE MIGR_TB_REV_CHANGES (ID_PK BIGINT AUTO_INCREMENT NOT NULL, REV BIGINT NULL, AUDIT_ORDER INT NULL, ENTITY_NAME VARCHAR(255) NULL, GROUP_NAME VARCHAR(255) NULL, ENTITY_ID VARCHAR(255) NULL, MODIFICATION_TYPE VARCHAR(255) NULL, CREATION_TIME timestamp DEFAULT (UTC_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR(255) DEFAULT 'DOMIBUS' NOT NULL, MODIFICATION_TIME timestamp NULL, MODIFIED_BY VARCHAR(255) NULL, CONSTRAINT PK_REV_CHANGES PRIMARY KEY (ID_PK));

CREATE TABLE MIGR_TB_COMMAND (ID_PK BIGINT AUTO_INCREMENT NOT NULL, SERVER_NAME VARCHAR(255) NOT NULL COMMENT 'The target server name', COMMAND_NAME VARCHAR(255) NOT NULL, CREATION_TIME timestamp DEFAULT (UTC_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR(255) DEFAULT 'DOMIBUS' NOT NULL, MODIFICATION_TIME timestamp NULL, MODIFIED_BY VARCHAR(255) NULL, CONSTRAINT PK_COMMAND PRIMARY KEY (ID_PK)) COMMENT='Stores commands to be executed by different nodes in clustered environments';

CREATE TABLE MIGR_TB_COMMAND_PROPERTY (PROPERTY_NAME VARCHAR(50) NOT NULL, PROPERTY_VALUE VARCHAR(255) NULL, FK_COMMAND BIGINT NOT NULL COMMENT 'Reference to the parent command', CREATION_TIME timestamp DEFAULT (UTC_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR(255) DEFAULT 'DOMIBUS' NOT NULL, MODIFICATION_TIME timestamp NULL, MODIFIED_BY VARCHAR(255) NULL) COMMENT='Stores properties/parameters of the commands to be executed by different nodes in clustered environments';

CREATE TABLE MIGR_TB_ALERT (ID_PK BIGINT AUTO_INCREMENT NOT NULL, ALERT_TYPE VARCHAR(50) NOT NULL, ATTEMPTS_NUMBER INT NULL, MAX_ATTEMPTS_NUMBER INT NOT NULL, PROCESSED BIT(1) NULL, PROCESSED_TIME timestamp NULL, REPORTING_TIME timestamp NULL, REPORTING_TIME_FAILURE timestamp NULL, NEXT_ATTEMPT timestamp NULL, FK_TIMEZONE_OFFSET BIGINT NULL, ALERT_STATUS VARCHAR(50) NOT NULL, ALERT_LEVEL VARCHAR(20) NOT NULL, CREATION_TIME timestamp DEFAULT (UTC_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR(255) DEFAULT 'DOMIBUS' NOT NULL, MODIFICATION_TIME timestamp NULL, MODIFIED_BY VARCHAR(255) NULL, CONSTRAINT PK_ALERT PRIMARY KEY (ID_PK));

CREATE TABLE MIGR_TB_EVENT (ID_PK BIGINT AUTO_INCREMENT NOT NULL, EVENT_TYPE VARCHAR(50) NOT NULL, REPORTING_TIME timestamp NULL, LAST_ALERT_DATE timestamp NULL, CREATION_TIME timestamp DEFAULT (UTC_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR(255) DEFAULT 'DOMIBUS' NOT NULL, MODIFICATION_TIME timestamp NULL, MODIFIED_BY VARCHAR(255) NULL, CONSTRAINT PK_EVENT PRIMARY KEY (ID_PK));

CREATE TABLE MIGR_TB_EVENT_ALERT (FK_EVENT BIGINT NOT NULL, FK_ALERT BIGINT NOT NULL, CREATION_TIME timestamp DEFAULT (UTC_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR(255) DEFAULT 'DOMIBUS' NOT NULL, MODIFICATION_TIME timestamp NULL, MODIFIED_BY VARCHAR(255) NULL, CONSTRAINT PK_EVENT_ALERT PRIMARY KEY (FK_EVENT, FK_ALERT));

CREATE TABLE MIGR_TB_EVENT_PROPERTY (ID_PK BIGINT AUTO_INCREMENT NOT NULL, PROPERTY_TYPE VARCHAR(50) NOT NULL, FK_EVENT BIGINT NOT NULL, DTYPE VARCHAR(31) NULL, STRING_VALUE VARCHAR(255) NULL, DATE_VALUE timestamp NULL, CREATION_TIME timestamp DEFAULT (UTC_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR(255) DEFAULT 'DOMIBUS' NOT NULL, MODIFICATION_TIME timestamp NULL, MODIFIED_BY VARCHAR(255) NULL, CONSTRAINT PK_EVENT_PROPERTY PRIMARY KEY (ID_PK));

CREATE TABLE MIGR_TB_USER (ID_PK BIGINT AUTO_INCREMENT NOT NULL, USER_EMAIL VARCHAR(255) NULL, USER_ENABLED BIT(1) NOT NULL, USER_PASSWORD VARCHAR(255) NOT NULL, USER_NAME VARCHAR(255) NOT NULL, OPTLOCK INT NULL, ATTEMPT_COUNT INT DEFAULT 0 NULL, SUSPENSION_DATE timestamp NULL, USER_DELETED BIT(1) DEFAULT 0 NOT NULL, PASSWORD_CHANGE_DATE timestamp DEFAULT (UTC_TIMESTAMP) NOT NULL, DEFAULT_PASSWORD BIT(1) DEFAULT 0 NULL, CREATION_TIME timestamp DEFAULT (UTC_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR(255) DEFAULT 'DOMIBUS' NOT NULL, MODIFICATION_TIME timestamp NULL, MODIFIED_BY VARCHAR(255) NULL, CONSTRAINT PK_USER PRIMARY KEY (ID_PK));

CREATE TABLE MIGR_TB_USER_PASSWORD_HISTORY (ID_PK BIGINT AUTO_INCREMENT NOT NULL, USER_ID BIGINT NOT NULL, USER_PASSWORD VARCHAR(255) NOT NULL, PASSWORD_CHANGE_DATE timestamp NULL, CREATION_TIME timestamp DEFAULT (UTC_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR(255) DEFAULT 'DOMIBUS' NOT NULL, MODIFICATION_TIME timestamp NULL, MODIFIED_BY VARCHAR(255) NULL, CONSTRAINT PK_USER_PASSWORD_HISTORY PRIMARY KEY (ID_PK));

CREATE TABLE MIGR_TB_USER_ROLE (ID_PK BIGINT AUTO_INCREMENT NOT NULL, ROLE_NAME VARCHAR(255) NOT NULL, CREATION_TIME timestamp DEFAULT (UTC_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR(255) DEFAULT 'DOMIBUS' NOT NULL, MODIFICATION_TIME timestamp NULL, MODIFIED_BY VARCHAR(255) NULL, CONSTRAINT PK_USER_ROLE PRIMARY KEY (ID_PK));

CREATE TABLE MIGR_TB_USER_ROLES (USER_ID BIGINT NOT NULL, ROLE_ID BIGINT NOT NULL, CREATION_TIME timestamp DEFAULT (UTC_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR(255) DEFAULT 'DOMIBUS' NOT NULL, MODIFICATION_TIME timestamp NULL, MODIFIED_BY VARCHAR(255) NULL, CONSTRAINT PK_PRIMARY PRIMARY KEY (USER_ID, ROLE_ID));

CREATE TABLE MIGR_TB_USER_ROLES_AUD (REV BIGINT NULL, REVTYPE TINYINT NULL, USER_ID BIGINT NULL, ROLE_ID BIGINT NULL);

--  Changeset src/main/resources/db/archive/5.0/migration/multitenancy/changelog-42-50-data-migration-step1.xml::EDELIVERY-7970-prepare-multitenancy::Catalin Enache
--  drop previously created tables for migration - MIGR_* and TB_D tables
DROP TABLE IF EXISTS MIGR_TB_USER_DOMAIN
//

--  Changeset src/main/resources/db/archive/5.0/migration/multitenancy/changelog-42-50-data-migration-step1.xml::EDELIVERY-8441-recreate-MIGR-tables-for-primary-key-migration-multitenancy::Sebastian-Ion TINCU
CREATE TABLE MIGR_TB_USER_DOMAIN (ID_PK BIGINT AUTO_INCREMENT NOT NULL, USER_NAME VARCHAR(255) NULL, DOMAIN VARCHAR(255) NULL, PREFERRED_DOMAIN VARCHAR(255) NULL, CREATION_TIME timestamp DEFAULT (UTC_TIMESTAMP) NOT NULL, CREATED_BY VARCHAR(255) DEFAULT 'DOMIBUS' NOT NULL, MODIFICATION_TIME timestamp NULL, MODIFIED_BY VARCHAR(255) NULL, CONSTRAINT PK_USER_DOMAIN PRIMARY KEY (ID_PK));

CREATE TABLE MIGR_TB_USER_AUD (ID_PK BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE TINYINT NULL, USER_ENABLED BIT(1) NULL, ACTIVE_MOD BIT(1) NULL, USER_DELETED BIT(1) NULL, DELETED_MOD BIT(1) NULL, USER_EMAIL VARCHAR(255) NULL, EMAIL_MOD BIT(1) NULL, USER_PASSWORD VARCHAR(255) NULL, PASSWORD_MOD BIT(1) NULL, USER_NAME VARCHAR(255) NULL, USERNAME_MOD BIT(1) NULL, OPTLOCK INT NULL, VERSION_MOD BIT(1) NULL, ROLES_MOD BIT(1) NULL, PASSWORD_CHANGE_DATE timestamp NULL, PASSWORDCHANGEDATE_MOD BIT(1) NULL, DEFAULT_PASSWORD BIT(1) NULL, DEFAULTPASSWORD_MOD BIT(1) NULL, CONSTRAINT PK_USER_AUD PRIMARY KEY (ID_PK, REV));

CREATE TABLE MIGR_TB_USER_ROLE_AUD (ID_PK BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE TINYINT NULL, ROLE_NAME VARCHAR(255) NULL, NAME_MOD BIT(1) NULL, USERS_MOD BIT(1) NULL, CONSTRAINT PK_USER_ROLE_AUD PRIMARY KEY (ID_PK, REV));

--  Changeset src/main/resources/db/archive/5.0/migration/multitenancy/changelog-42-50-data-migration-step1.xml::EDELIVERY-7849-Migrate-Timestamp-to-UTC-multitenancy::Soumya
