#!/command/with-contenv bash
set -euo pipefail

source /usr/lib/harmony-common
source /usr/lib/harmony-cluster

readonly STAGE="init-webserver"

: "${TLS_PUBLIC_CERT_NAME:=tls}"
: "${TLS_PUBLIC_CERT_PATH:=${CERT_DIR%/}/$TLS_PUBLIC_CERT_NAME-$CERT_ALIAS.cer}"
: "${TLS_KEYSTORE_PATH:=${HARMONY_BASE}/etc/tls-keystore.p12}"
: "${TLS_TRUSTSTORE_PATH:=${HARMONY_BASE}/etc/tls-truststore.p12}"

get_server_prop() {
  local property_name="$1"
  local default="${2:-}"
  local value

  value=$(xmlstarlet sel -t -v "//Connector/@$property_name" "$HARMONY_BASE/conf/server.xml" 2>/dev/null || true)
  echo "${value:-$default}";
}

setup_default_conf() {
  cp --update=none "$HARMONY_HOME/setup/server.xml.template"               "$HARMONY_BASE/conf/server.xml"
  cp --update=none "$HARMONY_HOME/setup/clientauthentication.xml.template" "$HARMONY_BASE/etc/clientauthentication.xml"

  chmod 600 "$HARMONY_BASE/conf/server.xml"
  chmod 600 "$HARMONY_BASE/etc/clientauthentication.xml"
}

obtain_tls_store_password() {
  local store_type="$1"
  local password="$2"
  local secret_name="$3"

  log "DEBUG" "Determining tls $store_type password"

  local store_pass
  store_pass=$(
    harmony-password \
      --stage "$STAGE" \
      --mode determine \
      --password-value "$password" \
      --current-password "$(read_secret "$secret_name")"
  )

  echo "$store_pass"
}

manage_tls_certificates() {
  log "DEBUG" "Handling tls certificates"

  TLS_KEYSTORE_BASE64="${TLS_KEYSTORE_BASE64:-}"
  TLS_TRUSTSTORE_BASE64="${TLS_TRUSTSTORE_BASE64:-}"

  SERVER_FQDN="${SERVER_FQDN:-$(hostname -f)}"
  SERVER_DN="${SERVER_DN:-CN=$SERVER_FQDN}"
  SERVER_SAN="${SERVER_SAN:-DNS:$SERVER_FQDN}"

  harmony-store \
    --stage "$STAGE" \
    --keystore-path "$TLS_KEYSTORE_PATH" \
    --keystore-password "$TLS_KEYSTORE_PASSWORD" \
    --keystore-base64 "$TLS_KEYSTORE_BASE64" \
    --truststore-path "$TLS_TRUSTSTORE_PATH" \
    --truststore-password "$TLS_TRUSTSTORE_PASSWORD" \
    --truststore-base64 "$TLS_TRUSTSTORE_BASE64" \
    --should-add-certificate-to-truststore "true" \
    --alias "$CERT_ALIAS" \
    --public-cert-path "$TLS_PUBLIC_CERT_PATH" \
    --dname "$SERVER_DN" \
    --san "$SERVER_SAN"
}

determine_ssl_configuration() {
  log "DEBUG" "Determining SSL configuration"
  local ssl_enabled=true
  local port=8443

  EXTERNAL_LB="${EXTERNAL_LB:-false}"
  if [[ "$DEPLOYMENT_CLUSTERED" == "true" || "$EXTERNAL_LB" == "true" ]]; then
    ssl_enabled=false
    port=8080
  fi

  log "INFO" "Server configuration:"
  log "INFO" "    SSL enabled: $ssl_enabled"
  log "INFO" "    Port: $port"

  printf "%s" "$ssl_enabled" > /var/run/s6/container_environment/SSL_ENABLED
  printf "%s" "$port" > /var/run/s6/container_environment/PORT

  echo "$ssl_enabled $port"
}

update_server_configuration() {
  local ssl_enabled="$1"
  local port="$2"

  log "DEBUG" "Updating server configuration"

  xmlstarlet edit --pf \
    --update '//Connector/@SSLEnabled'      --value "$ssl_enabled" \
    --update '//Connector/@port'            --value "$port" \
    --update '//Connector/@keystorePass'    --value "$TLS_KEYSTORE_PASSWORD" \
    --update '//Connector/@keystoreFile'    --value "$TLS_KEYSTORE_PATH" \
    --update '//Connector/@truststorePass'  --value "$TLS_TRUSTSTORE_PASSWORD" \
    --update '//Connector/@keyAlias'        --value "$CERT_ALIAS" \
    --insert '//Connector[not(@keyAlias)]'  --type attr -n keyAlias -v "$CERT_ALIAS" \
    "$HARMONY_BASE/conf/server.xml" > "$TEMP_DIR/server.xml"
  cp "$TEMP_DIR/server.xml" "$HARMONY_BASE/conf/server.xml"
}

update_server_security_configuration() {
  log "DEBUG" "Updating server security configuration"

  xmlstarlet edit --pf \
    -N s='http://cxf.apache.org/configuration/security' \
    --update '//s:trustManagers/s:keyStore/@password' --value "$TLS_TRUSTSTORE_PASSWORD" \
    --update '//s:trustManagers/s:keyStore/@file'     --value "$TLS_TRUSTSTORE_PATH" \
    --update '//s:keyManagers/s:keyStore/@password'   --value "$TLS_KEYSTORE_PASSWORD" \
    --update '//s:keyManagers/s:keyStore/@file'       --value "$TLS_KEYSTORE_PATH" \
    "$HARMONY_BASE/etc/clientauthentication.xml" > "$TEMP_DIR/clientauthentication.xml"
  cp "$TEMP_DIR/clientauthentication.xml" "$HARMONY_BASE/etc/clientauthentication.xml"
}

synchronize_secrets() {
  if is_primary; then
    log "DEBUG" "Primary node: storing secrets"

    store_secret "TLS-KEYSTORE-PASSWORD"    "$TLS_KEYSTORE_PASSWORD"
    store_secret "TLS-TRUSTSTORE-PASSWORD"  "$TLS_TRUSTSTORE_PASSWORD"
    store_secret "TLS-KEYSTORE-FILE"        "$TLS_KEYSTORE_PATH"
    store_secret "TLS-TRUSTSTORE-FILE"      "$TLS_TRUSTSTORE_PATH"
    store_secret "TLS-PUBLIC-CERT-FILE"     "$TLS_PUBLIC_CERT_PATH"
  else
    log "DEBUG" "Replica node: reading secret"

    TLS_KEYSTORE_PASSWORD=$(read_secret "TLS-KEYSTORE-PASSWORD")
    TLS_TRUSTSTORE_PASSWORD=$(read_secret "TLS-TRUSTSTORE-PASSWORD")

    read_secret "TLS-KEYSTORE-FILE"     "$TLS_KEYSTORE_PATH"
    read_secret "TLS-TRUSTSTORE-FILE"   "$TLS_TRUSTSTORE_PATH"
    read_secret "TLS-PUBLIC-CERT-FILE"  "$TLS_PUBLIC_CERT_PATH"
  fi
}

init_webserver() {
  log "DEBUG" "Started"
  setup_default_conf

  if is_primary; then
    log "DEBUG" "Primary node: processing TLS certificates"

    TLS_KEYSTORE_PASSWORD=$(obtain_tls_store_password "keystore" "${TLS_KEYSTORE_PASSWORD:-}" "TLS-KEYSTORE-PASSWORD")
    TLS_TRUSTSTORE_PASSWORD=$(obtain_tls_store_password "truststore" "${TLS_TRUSTSTORE_PASSWORD:-}" "TLS-TRUSTSTORE-PASSWORD")
    manage_tls_certificates
  fi

  synchronize_secrets

  printf "%s" "$TLS_TRUSTSTORE_PASSWORD" > /var/run/s6/container_environment/TLS_TRUSTSTORE_PASSWORD
  printf "%s" "$TLS_TRUSTSTORE_PATH"    > /var/run/s6/container_environment/TLS_TRUSTSTORE_PATH

  read -r ssl_enabled port <<< "$(determine_ssl_configuration)"
  update_server_configuration "$ssl_enabled" "$port"
  update_server_security_configuration

  log "DEBUG" "Done"
}

init_webserver