#!/command/with-contenv bash
set -euo pipefail

readonly STAGE="init-webserver"

: "${CERT_DIR:=${HARMONY_BASE}/etc/certs}"
: "${TLS_KEYSTORE_PATH:=${HARMONY_BASE}/etc/tls-keystore.p12}"
: "${TLS_TRUSTSTORE_PATH:=${HARMONY_BASE}/etc/tls-truststore.p12}"

log() {
  local level="$1"
  local message="$2"
  harmony-log "$level" "$STAGE" "$message" >&2
}

get_server_prop() {
  local property_name="$1"
  local default="${2:-}"
  local value

  value=$(xmlstarlet sel -t -v "//Connector/@$property_name" "$HARMONY_BASE/conf/server.xml" 2>/dev/null || true)
  echo "${value:-$default}";
}

setup_default_conf() {
  cp --update=none "$HARMONY_HOME/setup/server.xml.template"               "$HARMONY_BASE/conf/server.xml"
  cp --update=none "$HARMONY_HOME/setup/clientauthentication.xml.template" "$HARMONY_BASE/etc/clientauthentication.xml"

  chmod 600 "$HARMONY_BASE/conf/server.xml"
  chmod 600 "$HARMONY_BASE/etc/clientauthentication.xml"
}

obtain_tls_keystore_password() {
  log "DEBUG" "Determining tls keystore password"

  local keystore_pass
  keystore_pass=$(
    harmony-password \
      --stage "$STAGE" \
      --mode determine \
      --password-value "${TLS_KEYSTORE_PASSWORD:-}" \
      --current-password "$(get_server_prop 'keystorePass')"
  )

  echo "$keystore_pass"
}

obtain_tls_truststore_password() {
  log "DEBUG" "Determining tls truststore password"

  local truststore_pass
  truststore_pass=$(
    harmony-password \
      --stage "$STAGE" \
      --mode determine \
      --password-value "${TLS_TRUSTSTORE_PASSWORD:-}" \
      --current-password "$(get_server_prop 'truststorePass')"
  )

  printf "%s" "$truststore_pass" > /var/run/s6/container_environment/TLS_TRUSTSTORE_PASSWORD

  echo "$truststore_pass"
}

manage_tls_stores() {
  local tls_keystore_password="$1"
  local tls_truststore_password="$2"

  log "DEBUG" "Handling tls certificates"

  local alias="${PARTY_NAME:-selfsigned}"
  TLS_KEYSTORE_BASE64="${TLS_KEYSTORE_BASE64:-}"
  TLS_TRUSTSTORE_BASE64="${TLS_TRUSTSTORE_BASE64:-}"

  printf "%s" "$TLS_TRUSTSTORE_PATH" > /var/run/s6/container_environment/TLS_TRUSTSTORE_PATH

  SERVER_FQDN="${SERVER_FQDN:-$(hostname -f)}"
  SERVER_DN="${SERVER_DN:-CN=$SERVER_FQDN}"
  SERVER_SAN="${SERVER_SAN:-DNS:$SERVER_FQDN}"

  harmony-store \
    --stage "$STAGE" \
    --cert-dir "$CERT_DIR" \
    --keystore-path "$TLS_KEYSTORE_PATH" \
    --keystore-password "$tls_keystore_password" \
    --keystore-base64 "$TLS_KEYSTORE_BASE64" \
    --truststore-path "$TLS_TRUSTSTORE_PATH" \
    --truststore-password "$tls_truststore_password" \
    --truststore-base64 "$TLS_TRUSTSTORE_BASE64" \
    --should-add-certificate-to-truststore "true" \
    --alias "$alias" \
    --public-cert-name "tls" \
    --dname "$SERVER_DN" \
    --san "$SERVER_SAN"
}

determine_ssl_configuration() {
  log "DEBUG" "Determining SSL configuration"
  local ssl_enabled=true
  local port=8443

  EXTERNAL_LB="${EXTERNAL_LB:-false}"
  if [[ "$DEPLOYMENT_CLUSTERED" == "true" || "$EXTERNAL_LB" == "true" ]]; then
    ssl_enabled=false
    port=8080
  fi

  log "INFO" "Server configuration:"
  log "INFO" "    SSL enabled: $ssl_enabled"
  log "INFO" "    Port: $port"

  printf "%s" "$ssl_enabled" > /var/run/s6/container_environment/SSL_ENABLED
  printf "%s" "$port" > /var/run/s6/container_environment/PORT

  echo "$ssl_enabled $port"
}

update_server_configuration() {
  local tls_keystore_password="$1"
  local tls_truststore_password="$2"
  local ssl_enabled="$3"
  local port="$4"

  log "DEBUG" "Updating server configuration"

  xmlstarlet edit --pf \
    --update '//Connector/@SSLEnabled'     --value "$ssl_enabled" \
    --update '//Connector/@port'           --value "$port" \
    --update '//Connector/@keystorePass'   --value "$tls_keystore_password" \
    --update '//Connector/@keystoreFile'   --value "$TLS_KEYSTORE_PATH" \
    --update '//Connector/@truststorePass' --value "$tls_truststore_password" \
    "$HARMONY_BASE/conf/server.xml" > "$TEMP_DIR/server.xml"
  cp "$TEMP_DIR/server.xml" "$HARMONY_BASE/conf/server.xml"
}

update_server_security_configuration() {
  local tls_keystore_password="$1"
  local tls_truststore_password="$2"

  log "DEBUG" "Updating server security configuration"

  xmlstarlet edit --pf \
    -N s='http://cxf.apache.org/configuration/security' \
    --update '//s:trustManagers/s:keyStore/@password' --value "$tls_truststore_password" \
    --update '//s:trustManagers/s:keyStore/@file'     --value "$TLS_TRUSTSTORE_PATH" \
    --update '//s:keyManagers/s:keyStore/@password'   --value "$tls_keystore_password" \
    --update '//s:keyManagers/s:keyStore/@file'       --value "$TLS_KEYSTORE_PATH" \
    "$HARMONY_BASE/etc/clientauthentication.xml" > "$TEMP_DIR/clientauthentication.xml"
  cp "$TEMP_DIR/clientauthentication.xml" "$HARMONY_BASE/etc/clientauthentication.xml"
}

init_webserver() {
  log "DEBUG" "Started"
  setup_default_conf

  local tls_keystore_password
  tls_keystore_password=$(obtain_tls_keystore_password)
  local tls_truststore_password
  tls_truststore_password=$(obtain_tls_truststore_password)
  manage_tls_stores "$tls_keystore_password" "$tls_truststore_password"

  read -r ssl_enabled port <<< "$(determine_ssl_configuration)"
  update_server_configuration "$tls_keystore_password" "$tls_truststore_password" "$ssl_enabled" "$port"
  update_server_security_configuration "$tls_keystore_password" "$tls_truststore_password"

  log "DEBUG" "Done"
}

init_webserver