FROM maven:3.6-jdk-8
LABEL maintainer="Nordic Institute for Interoperability Solutions <edelivery@niis.org>"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update \
  && apt-get -qq upgrade

ARG uid
ARG gid

RUN groupadd -g $gid builder && useradd -m -u $uid -g $gid builder
RUN mkdir -p /root && chown -R builder:builder /root
RUN mkdir -p /home/builder/.m2 && chown -R builder:builder /home/builder/.m2

USER builder

WORKDIR /mnt
