FROM ubuntu:22.04
LABEL maintainer="Nordic Institute for Interoperability Solutions <edelivery@niis.org>"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update \
  && apt-get -qq upgrade \
  && apt-get -qq install openjdk-8-jdk dpkg-dev devscripts debhelper \
  && apt-get -qq autoremove \
  && apt-get -qq clean

ARG uid
ARG gid

RUN groupadd -g $gid builder && useradd -m -u $uid -g $gid builder
RUN mkdir -p /home/builder/.m2 && chown -R builder:builder /home/builder/.m2

USER builder
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
WORKDIR /mnt
