FROM maven:3.6-jdk-8
LABEL maintainer="Nordic Institute for Interoperability Solutions <edelivery@niis.org>"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update \
  && apt-get -qq upgrade \
  && apt-get -qq install tzdata \
  && apt-get -qq autoremove \
  && apt-get -qq clean \
  && ln -fs /usr/share/zoneinfo/EET /etc/localtime \
  && dpkg-reconfigure -f noninteractive tzdata

ARG uid
ARG gid

RUN groupadd -g $gid builder && useradd -m -u $uid -g $gid builder
RUN mkdir -p /root && chown -R builder:builder /root
RUN mkdir -p /.m2 && chown -R builder:builder /.m2

USER builder

WORKDIR /mnt