events {
  worker_connections  1024;
}

http {
  upstream ap_stateless {
    server harmony-ap-luke:8080;
    server harmony-ap-leia:8080;
  }

  upstream ap_sticky {
    ip_hash;
    server harmony-ap-luke:8080;
    server harmony-ap-leia:8080;
  }

  server {
    listen       443 ssl;

    ssl_certificate      /etc/nginx/certs/harmony-ap-tls.crt;
    ssl_certificate_key  /etc/nginx/certs/harmony-ap-tls.key;

    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;

    location ^~ /services/ {
      proxy_pass http://ap_stateless;
    }

    location / {
      proxy_pass http://ap_sticky;
    }
  }
}