insert ignore into SMP_USER (ID, USERNAME, PASSWORD, ROLE, ACTIVE, CREATED_ON, LAST_UPDATED_ON, PASSWORD_CHANGED) values (1, 'system', '$2a$06$FDmjewn/do3C219uysNm9.XG8mIn.ubHnMydAzC8lsv61HsRpOR36', 'SYSTEM_ADMIN', 1, NOW(), NOW(), NOW());
insert ignore into SMP_USER (ID, USERNAME, PASSWORD, ROLE, ACTIVE, CREATED_ON, LAST_UPDATED_ON, PASSWORD_CHANGED) values (2, 'smp', '$2a$06$FDmjewn/do3C219uysNm9.XG8mIn.ubHnMydAzC8lsv61HsRpOR36', 'SMP_ADMIN', 1, NOW(), NOW(), NOW());
insert ignore into SMP_USER (ID, USERNAME, PASSWORD, ROLE, ACTIVE, CREATED_ON, LAST_UPDATED_ON, PASSWORD_CHANGED) values (3, 'user', '$2a$06$FDmjewn/do3C219uysNm9.XG8mIn.ubHnMydAzC8lsv61HsRpOR36', 'SERVICE_GROUP_ADMIN', 1, NOW(), NOW(), NOW());

UPDATE SMP_USER_SEQ set next_val=4 WHERE next_val < 4;

INSERT INTO SMP_DOMAIN (ID, DOMAIN_CODE, SML_SUBDOMAIN, SML_SMP_ID, SIGNATURE_KEY_ALIAS, SML_BLUE_COAT_AUTH,SML_REGISTERED, CREATED_ON, LAST_UPDATED_ON) values (1, 'smpa','smpa.neds','NEDS-SMP-A', '{{inventory_hostname}}', 1,0, NOW(), NOW())
  ON DUPLICATE KEY UPDATE DOMAIN_CODE='smpa', SML_SUBDOMAIN='smpa.neds', SML_SMP_ID='NEDS-SMP-A', SIGNATURE_KEY_ALIAS='{{inventory_hostname}}', SML_BLUE_COAT_AUTH=1, LAST_UPDATED_ON=NOW();

UPDATE SMP_DOMAIN_SEQ set next_val=2 WHERE next_val < 2;

DELETE FROM SMP_CONFIGURATION;

INSERT INTO SMP_CONFIGURATION (PROPERTY, VALUE, CREATED_ON, LAST_UPDATED_ON) VALUES ('contextPath.output', 'true', NOW(), NOW());
INSERT INTO SMP_CONFIGURATION (PROPERTY, VALUE, CREATED_ON, LAST_UPDATED_ON) VALUES ('bdmsl.integration.enabled', 'true', NOW(), NOW());
INSERT INTO SMP_CONFIGURATION (PROPERTY, VALUE, CREATED_ON, LAST_UPDATED_ON) VALUES ('bdmsl.integration.url', 'http://{{sml_hostname}}:8080/', NOW(), NOW());
INSERT INTO SMP_CONFIGURATION (PROPERTY, VALUE, CREATED_ON, LAST_UPDATED_ON) VALUES ('bdmsl.integration.tls.disableCNCheck', 'true', NOW(), NOW());
INSERT INTO SMP_CONFIGURATION (PROPERTY, VALUE, CREATED_ON, LAST_UPDATED_ON) VALUES ('bdmsl.integration.logical.address', 'http://{{smp_hostname}}:8080/', NOW(), NOW());
INSERT INTO SMP_CONFIGURATION (PROPERTY, VALUE, CREATED_ON, LAST_UPDATED_ON) VALUES ('bdmsl.integration.physical.address', '{{smp_ip}}', NOW(), NOW());
INSERT INTO SMP_CONFIGURATION (PROPERTY, VALUE, CREATED_ON, LAST_UPDATED_ON) VALUES ('bdmsl.integration.tls.serverSubjectRegex', '', NOW(), NOW());
INSERT INTO SMP_CONFIGURATION (PROPERTY, VALUE, CREATED_ON, LAST_UPDATED_ON) VALUES ('smp.keystore.filename', 'smp-keystore.jks', NOW(), NOW());
INSERT INTO SMP_CONFIGURATION (PROPERTY, VALUE, CREATED_ON, LAST_UPDATED_ON) VALUES ('smp.keystore.password', '{DEC}{password}', NOW(), NOW());
INSERT INTO SMP_CONFIGURATION (PROPERTY, VALUE, CREATED_ON, LAST_UPDATED_ON) VALUES ('authentication.blueCoat.enabled', 'true', NOW(), NOW());
INSERT INTO SMP_CONFIGURATION (PROPERTY, VALUE, CREATED_ON, LAST_UPDATED_ON) VALUES ('configuration.dir', '/opt/tomcat/custom_conf/', NOW(), NOW());


