#!/command/with-contenv bash
set -euo pipefail

readonly STAGE="init-database"

source /usr/lib/harmony-common
source /usr/lib/harmony-cluster

readonly DEFAULT_ADMIN_USER="harmony"

define_liquibase_parameters() {
  liquibase_home="${HARMONY_HOME}/liquibase"
  search_path="${HARMONY_HOME}/db"
  changelog_file="db.changelog.xml"

  classpath="$liquibase_home"

  drivers=(
    "${HARMONY_HOME}/lib/mysql-connector-j.jar"
    "${HARMONY_HOME}/lib/mariadb-java-client.jar"
  )

  for driver in "${drivers[@]}"; do
    if [[ -f "$driver" ]]; then
      classpath="$classpath:$driver"
    fi
  done

  if [[ "$LOG_LEVEL" == "DEBUG" ]]; then
    sql_warnings=true
  else
    sql_warnings=false
  fi

  liquibase_common_args=(
    --driver="$DB_DRIVER_CLASS"
    --classpath="$classpath"
    --search-path="$search_path"
    --changelog-file="$changelog_file"
    --url="$DB_URL"
    --username="$DB_USER"
    --password="$DB_PASSWORD"
    --show-banner=false
    --analytics-enabled=false
    --sql-show-sql-warnings="$sql_warnings"
  )
}

run_migrations() {
  local _admin_user _admin_password _admin_password_hash history_output

  _admin_user="${ADMIN_USER:-$DEFAULT_ADMIN_USER}"
  _admin_password="${ADMIN_PASSWORD:-}"

  if ! history_output=$("$liquibase_home/liquibase" "${liquibase_common_args[@]}" history 2>&1); then
    log ERROR "Failed to execute 'liquibase history'. Database may be unreachable or misconfigured."

    printf "\n\n%s\n" "$history_output" >&2
    exit 1
  fi

  if grep -q "No changesets deployed" <<< "$history_output"; then
    log INFO "Database not initialized. Running migrations for the first time"

    log DEBUG "Defining admin user credentials"

    if [[ -z "$_admin_password" ]]; then
      _admin_password=$(harmony-password --stage "$STAGE")
    fi

    if [[ -z "${ADMIN_PASSWORD:-}" ]]; then
      log INFO "Harmony AP admin credentials:"
      log INFO "    Username: $_admin_user"
      log INFO "    Password: $_admin_password"
    fi

    log DEBUG "Hashing admin password"
    _admin_password_hash=$(java -cp "${HARMONY_HOME}/webapps/ROOT/WEB-INF/lib/*" \
      eu.domibus.api.util.BCryptPasswordHash "$_admin_password")

    log DEBUG "Applying database migrations"
    "$liquibase_home/liquibase" "${liquibase_common_args[@]}" update \
      -DADMIN_USERNAME="$_admin_user" \
      -DADMIN_PASSWORD_HASH="$_admin_password_hash" \
      2>&1 | sed 's/^/    /'
  else
    log INFO "Database already initialized. Applying pending database migrations"
    "$liquibase_home/liquibase" "${liquibase_common_args[@]}" update \
      2>&1 | sed 's/^/    /'
  fi

  ADMIN_USER="$_admin_user"
  ADMIN_PASSWORD="$_admin_password"

  log INFO "Database migrations applied"
}

persist_database_connection_details() {
  set_property 'domibus.datasource.url' "$DB_URL"
  set_property "domibus.datasource.driverClassName" "$DB_DRIVER_CLASS"
  set_property 'domibus.database.schema' "$DB_SCHEMA"
  set_property 'domibus.database.serverName' "$DB_HOST"
  set_property 'domibus.database.port' "$DB_PORT"
  set_property 'domibus.datasource.user' "$DB_USER"
  set_property 'domibus.datasource.password' "$DB_PASSWORD" --quiet
}

sync_database_user() {
  if is_primary; then
    log DEBUG "Primary node: storing secrets"

    if [[ -n "${ADMIN_PASSWORD:-}" ]]; then
      log DEBUG "Admin password is set; storing as secret"
      store_secret "ADMIN-PASSWORD" "$ADMIN_PASSWORD"
    fi
  fi

  ADMIN_USER="${ADMIN_USER:-$DEFAULT_ADMIN_USER}"
  ADMIN_PASSWORD=${ADMIN_PASSWORD:-$(read_secret "ADMIN-PASSWORD")}
}

publish_environment_variables() {
  printf "%s" "$ADMIN_USER" > /var/run/s6/container_environment/ADMIN_USER
  printf "%s" "$ADMIN_PASSWORD" > /var/run/s6/container_environment/ADMIN_PASSWORD
}

init_database() {
  log DEBUG "Started"

  if is_primary; then
    define_liquibase_parameters
    run_migrations
  else
    log DEBUG "Not a primary node; skipping database initialization"
  fi

  sync_database_user
  persist_database_connection_details
  publish_environment_variables

  log DEBUG "Done"
}

init_database
