#!/command/with-contenv bash
set -euo pipefail

readonly STAGE="init-database"

source /usr/lib/harmony-ap/lib/harmony-common
source /usr/lib/harmony-ap/lib/harmony-cluster

: "${ADMIN_USER:=harmony}"

run_liquibase() {
  local args=(
    --mode liquibase
    --stage "$STAGE"
    --db-url "$DB_URL"
    --db-driver-class "$DB_DRIVER_CLASS"
    --db-user "$DB_USER"
    --indent-output
  )

  [[ "${LOG_LEVEL:-}" != "DEBUG" ]] || args+=(--sql-show-sql-warnings)

  DB_PASSWORD="$DB_PASSWORD" harmony-database "${args[@]}" -- "$@"
}

run_migrations() {
  local _admin_user _admin_password _admin_password_hash history_output

  _admin_user="$ADMIN_USER"
  _admin_password="${ADMIN_PASSWORD:-}"

  if ! history_output=$(run_liquibase history 2>&1); then
    log ERROR "Failed to execute 'liquibase history'. Database may be unreachable or misconfigured."

    printf "\n\n%s\n" "$history_output" >&2
    exit 1
  fi

  if grep -q "No changesets deployed" <<< "$history_output"; then
    log INFO "Database not initialized. Running migrations for the first time"

    log DEBUG "Defining admin user credentials"

    if [[ -z "$_admin_password" ]]; then
      _admin_password=$(harmony-password --stage "$STAGE" --label "admin")
    fi

    if [[ -z "${ADMIN_PASSWORD:-}" ]]; then
      log INFO "Harmony AP admin credentials:"
      log INFO "  Username: $_admin_user"
      log INFO "  Password: $_admin_password"
    fi

    log DEBUG "Hashing admin password"
    _admin_password_hash=$(java -cp "${HARMONY_HOME}/webapps/ROOT/WEB-INF/lib/*" \
      eu.domibus.api.util.BCryptPasswordHash "$_admin_password")

    log DEBUG "Applying database migrations"
    run_liquibase update \
      -DADMIN_USERNAME="$_admin_user" \
      -DADMIN_PASSWORD_HASH="$_admin_password_hash"
  else
    log INFO "Database already initialized. Applying pending database migrations"
    run_liquibase update
  fi

  ADMIN_USER="$_admin_user"
  ADMIN_PASSWORD="$_admin_password"

  log INFO "Database migrations applied"
}

sync_database_user() {
  if is_primary; then
    log DEBUG "Primary node: storing secrets"

    if [[ -n "${ADMIN_PASSWORD:-}" ]]; then
      log DEBUG "Admin password is set; storing as secret"
      store_secret "ADMIN-PASSWORD" "$ADMIN_PASSWORD"
    fi
  fi

  ADMIN_PASSWORD=${ADMIN_PASSWORD:-$(read_secret "ADMIN-PASSWORD")}
}

publish_admin_env() {
  publish_env ADMIN_USER "$ADMIN_USER"
  publish_env ADMIN_PASSWORD "$ADMIN_PASSWORD"
}

init_database() {
  log DEBUG "Started"

  if is_primary; then
    run_migrations
  else
    log DEBUG "Not a primary node; skipping database initialization"
  fi

  sync_database_user
  publish_admin_env

  log DEBUG "Done"
}

init_database
