#!/command/with-contenv bash
set -euo pipefail

readonly STAGE="init-domibus"

source /usr/lib/harmony-common
source /usr/lib/harmony-cluster

: "${WORK_LOCATION:=${HARMONY_BASE}/work}"
: "${DYNAMIC_DISCOVERY_FALLBACK:=false}"
: "${SECURITY_PUBLIC_CERT_NAME:=security}"
: "${SECURITY_PUBLIC_CERT_PATH:=${CERT_DIR%/}/$SECURITY_PUBLIC_CERT_NAME-$CERT_ALIAS.cer}"
: "${SECURITY_KEYSTORE_PATH:=${HARMONY_BASE}/etc/ap-keystore.p12}"
: "${SECURITY_TRUSTSTORE_PATH:=${HARMONY_BASE}/etc/ap-truststore.p12}"

detect_network_filesystem() {
  local fs_type
  fs_type=$(stat -f "${HARMONY_BASE}/etc" --format "%T")
  case "$fs_type" in
    cifs*|smb*|nfs*)
      log "WARN" "${HARMONY_BASE}/etc is on a network filesystem ($fs_type)"
      return 1
      ;;
    *)
      return 0
      ;;
  esac
}

setup_environment() {
  log "DEBUG" "Setting environment"

  PRESERVE_BACKUP_FILE_DATE=$(detect_network_filesystem && echo true || echo false)
  printf "%s" "$PRESERVE_BACKUP_FILE_DATE" > /var/run/s6/container_environment/PRESERVE_BACKUP_FILE_DATE
}

configure_cluster_settings() {
  log "DEBUG" "Configuring cluster if needed"

  WORK_LOCATION="${WORK_LOCATION%/}"
  if [[ "$DEPLOYMENT_CLUSTERED" == "true" ]]; then
    WORK_LOCATION="$WORK_LOCATION/${NODE_ID}"
  fi
  printf "%s" "$WORK_LOCATION" > /var/run/s6/container_environment/WORK_LOCATION
}

obtain_security_store_password() {
  local store_type="$1"
  local password="$2"
  local secret_name="$3"

  log "DEBUG" "Determining security $store_type password"

  local store_pass
  store_pass=$(
    harmony-password \
      --stage "$STAGE" \
      --mode determine \
      --password-value "$password" \
      --current-password "$(read_secret "$secret_name")"
  )

  echo "$store_pass"
}

manage_security_stores() {
  log "DEBUG" "Handling security certificates"

  SECURITY_KEYSTORE_BASE64="${SECURITY_KEYSTORE_BASE64:-}"
  SECURITY_TRUSTSTORE_BASE64="${SECURITY_TRUSTSTORE_BASE64:-}"

  SECURITY_DN="${SECURITY_DN:-CN=$PARTY_NAME}"

  harmony-store \
    --stage "$STAGE" \
    --keystore-path "$SECURITY_KEYSTORE_PATH" \
    --keystore-password "$SECURITY_KEYSTORE_PASSWORD" \
    --keystore-base64 "$SECURITY_KEYSTORE_BASE64" \
    --truststore-path "$SECURITY_TRUSTSTORE_PATH" \
    --truststore-password "$SECURITY_TRUSTSTORE_PASSWORD" \
    --truststore-base64 "$SECURITY_TRUSTSTORE_BASE64" \
    --should-add-certificate-to-truststore "false" \
    --alias "$CERT_ALIAS" \
    --public-cert-path "$SECURITY_PUBLIC_CERT_PATH" \
    --dname "$SECURITY_DN"
}

store_security_details() {
  set_property "domibus.deployment.clustered" "$DEPLOYMENT_CLUSTERED"
  set_property 'domibus.security.key.private.alias' "$CERT_ALIAS"

  SML_ZONE="${SML_ZONE:-$(get_property domibus.smlzone)}"
  set_property 'domibus.smlzone' "$SML_ZONE"

  USE_DYNAMIC_DISCOVERY="${USE_DYNAMIC_DISCOVERY:-$(get_property 'domibus.dynamicdiscovery.useDynamicDiscovery' "$DYNAMIC_DISCOVERY_FALLBACK")}"
  set_property 'domibus.dynamicdiscovery.useDynamicDiscovery' "$USE_DYNAMIC_DISCOVERY"
}

synchronize_secrets() {
  if is_primary; then
    log "DEBUG" "Primary node: storing secrets"

    store_secret "SECURITY-KEYSTORE-PASSWORD"    "$SECURITY_KEYSTORE_PASSWORD"
    store_secret "SECURITY-TRUSTSTORE-PASSWORD"  "$SECURITY_TRUSTSTORE_PASSWORD"
    store_secret "SECURITY-KEYSTORE-FILE"        "$SECURITY_KEYSTORE_PATH"
    store_secret "SECURITY-TRUSTSTORE-FILE"      "$SECURITY_TRUSTSTORE_PATH"
    store_secret "SECURITY-PUBLIC-CERT-FILE"     "$SECURITY_PUBLIC_CERT_PATH"
  else
    log "DEBUG" "Replica node: reading secret"

    SECURITY_KEYSTORE_PASSWORD=$(read_secret "SECURITY-KEYSTORE-PASSWORD")
    SECURITY_TRUSTSTORE_PASSWORD=$(read_secret "SECURITY-TRUSTSTORE-PASSWORD")

    read_secret "SECURITY-KEYSTORE-FILE"     "$SECURITY_KEYSTORE_PATH"
    read_secret "SECURITY-TRUSTSTORE-FILE"   "$SECURITY_TRUSTSTORE_PATH"
    read_secret "SECURITY-PUBLIC-CERT-FILE"  "$SECURITY_PUBLIC_CERT_PATH"
  fi
}

init_domibus() {
  log "DEBUG" "Started"

  setup_environment
  configure_cluster_settings

  if is_primary; then
    log "DEBUG" "Primary node: processing TLS certificates"

    SECURITY_KEYSTORE_PASSWORD=$(obtain_security_store_password "keystore" "${SECURITY_KEYSTORE_PASSWORD:-}" "SECURITY-KEYSTORE-PASSWORD")
    SECURITY_TRUSTSTORE_PASSWORD=$(obtain_security_store_password "truststore" "${SECURITY_TRUSTSTORE_PASSWORD:-}" "SECURITY-TRUSTSTORE-PASSWORD")
    manage_security_stores
  fi

  store_security_details

  synchronize_secrets

  set_property 'domibus.security.keystore.password' "$SECURITY_KEYSTORE_PASSWORD" --quiet
  set_property 'domibus.security.key.private.password' "$SECURITY_KEYSTORE_PASSWORD" --quiet
  set_property 'domibus.security.truststore.password' "$SECURITY_TRUSTSTORE_PASSWORD" --quiet

  log "DEBUG" "Done"
}

init_domibus