#!/command/with-contenv bash
set -euo pipefail

# shellcheck disable=SC2034 # Used in sourced scripts
readonly STAGE="init-messagebroker"

source /usr/lib/harmony-ap/lib/harmony-common

: "${ACTIVEMQ_EMBEDDED_CONFIG_PATH:=${HARMONY_CONFIG}/activemq.xml}"
: "${ACTIVEMQ_JMX_ACTIVE:=true}"
: "${ACTIVEMQ_JMX_PORT:=1199}"
: "${ACTIVEMQ_TRANSPORT_PORT:=61616}"
: "${ACTIVEMQ_BROKER_HOST:=localhost}"
: "${ACTIVEMQ_BROKER_NAME:=localhost}"

add_prefix_suffix() {
  local list="$1"
  local prefix="$2"
  local suffix="${3:-}"
  local result=""
  IFS=',' read -r -a items <<< "${list}"

  if [[ -z "${list}" ]]; then
    log WARN "No hosts provided"
    return
  fi

  for item in "${items[@]}"; do
    item="${item//[[:space:]]/}"
    if [[ -n "${item}" ]]; then
      result+="${prefix}${item}${suffix},"
    fi
  done

  echo "${result%,}"
}

construct_jmx_url() {
  local hosts="$1"
  local port="$2"

  add_prefix_suffix "${hosts}" "service:jmx:rmi:///jndi/rmi://" ":${port}/jmxrmi"
}

decode_from_base64() {
  log DEBUG "Decoding ActiveMQ configuration from Base64 using harmony-base64..."
  harmony-base64 --stage "$STAGE" --input "$ACTIVEMQ_EMBEDDED_CONFIG_B64" --output "$ACTIVEMQ_EMBEDDED_CONFIG_PATH" --force
}

configure_embedded_broker() {
  local broker_host="$1"

  if [ -n "${ACTIVEMQ_EMBEDDED_CONFIG_B64:-}" ]; then
    decode_from_base64
  elif [ -f "$ACTIVEMQ_EMBEDDED_CONFIG_PATH" ]; then
    log DEBUG "Using existing ActiveMQ configuration at '$ACTIVEMQ_EMBEDDED_CONFIG_PATH'"
  else
    die "ActiveMQ configuration not found at '$ACTIVEMQ_EMBEDDED_CONFIG_PATH'"
  fi

  publish_env ACTIVEMQ_EMBEDDED_CONFIGURATIONFILE "file:///${ACTIVEMQ_EMBEDDED_CONFIG_PATH}"

  echo "vm://${broker_host}"
}

configure_external_broker() {
  local broker_host="$1"
  log INFO "External broker detected"

  # Disable embedded broker
  publish_env ACTIVEMQ_EMBEDDED_CONFIGURATIONFILE ""

  local user="${ACTIVEMQ_USERNAME:-}"
  local pass="${ACTIVEMQ_PASSWORD:-}"

  if [ -n "$user" ]; then
    publish_env ACTIVEMQ_USERNAME "$user"
  fi
  if [ -n "$pass" ]; then
    publish_env ACTIVEMQ_PASSWORD "$pass"
  fi

  local hosts
  hosts="$(add_prefix_suffix "${broker_host}" "tcp://" ":${ACTIVEMQ_TRANSPORT_PORT}")"

  echo "failover:(${hosts})?randomize=false"
}

determine_transport_connector() {
  local broker_host="$1"
  log DEBUG "Configuring message broker"
  local transport_connector_uri

  if [[ "${broker_host}" == "localhost" ]]; then
    transport_connector_uri="$(configure_embedded_broker "${broker_host}")"
  else
    transport_connector_uri="$(configure_external_broker "${broker_host}")"
  fi

  echo "$transport_connector_uri"
}

publish_broker_env() {
  local transport_connector_uri="$1"
  local jmx_url="$2"

  log DEBUG "Publishing message broker environment variables"

  publish_env ACTIVEMQ_BROKERNAME "$ACTIVEMQ_BROKER_NAME"
  publish_env ACTIVEMQ_TRANSPORTCONNECTOR_URI "${transport_connector_uri}"
  publish_env ACTIVEMQ_JMX_ACTIVE "$ACTIVEMQ_JMX_ACTIVE"
  publish_env ACTIVEMQ_JMXURL "${jmx_url}"
}

init_messagebroker() {
  log DEBUG "Started"

  local jmx_url transport_connector_uri
  jmx_url="$(construct_jmx_url "$ACTIVEMQ_BROKER_HOST" "$ACTIVEMQ_JMX_PORT")"
  transport_connector_uri="$(determine_transport_connector "$ACTIVEMQ_BROKER_HOST")"

  publish_broker_env "$transport_connector_uri" "$jmx_url"

  log DEBUG "Done"
}

init_messagebroker
