#!/bin/bash
. /usr/share/debconf/confmodule

set -euo pipefail

escape_for_sed() {
    printf '%s\n' "$1" | sed -e 's/[\/&]/\\&/g'
}

SUCCESS=false
DROPDBONERROR=false

cleanup() {
  db_stop
  if [ ! "$SUCCESS" = true ]; then
    if [ "$DROPDBONERROR" = true ]; then
      mysql -e "DROP SCHEMA harmony_smp; DROP USER $DBUSER@localhost"
    fi;
  fi
}

trap cleanup EXIT

case "$1" in
 configure)

  db_get harmony-smp/serverdn
  SERVERDN="$RET"
  db_get harmony-smp/integratewithsml
  INTEGRATESML="$RET"
  if [ ! "$INTEGRATESML" = true ]; then
    INTEGRATESML=false
  fi
  db_get harmony-smp/smlurl
  SMLURL="$RET"
  db_get harmony-smp/smpurl
  SMPURL="$RET"
  db_get harmony-smp/smpip
  SMPIP="$RET"
  db_get harmony-smp/tomcatport
  TOMCATPORT="$RET"

  export LIQUIBASE_HOME=/opt/harmony-smp/liquibase
  export URL=jdbc:mysql://localhost:3306/harmony_smp
  export LIQUIBASE_SHOW_BANNER=false

  SCHEMA_EXISTS=$(mysql -s -N -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='harmony_smp'");
  if [ -z "$SCHEMA_EXISTS" ]; then

    db_input high harmony-smp/adminuser || true
    db_input high harmony-smp/adminpassword || true
    db_go

    db_get harmony-smp/adminuser
    AUSER="$RET"
    db_get harmony-smp/adminpassword
    APASSWORD="$RET"
    db_reset harmony-smp/adminpassword

    echo "Creating database schema harmony_smp" >&2

    DBUSER=harmony_smp
    DBPASSWORD=$(openssl rand -base64 12)

    mysql -e \
      "create schema harmony_smp; \
      alter database harmony_smp charset=utf8mb4 collate=utf8mb4_bin; \
      create user $DBUSER@localhost identified by '$DBPASSWORD'; \
      grant all on harmony_smp.* to $DBUSER@localhost;"
    DROPDBONERROR=true

    echo "Apply Liquibase migrations"  >&2

    HASHEDPASSWORD=$(java -cp "/opt/harmony-smp/webapps/ROOT/WEB-INF/lib/*" \
      eu.europa.ec.edelivery.smp.utils.BCryptPasswordHash "$APASSWORD")

    $LIQUIBASE_HOME/liquibase.sh \
      --classpath=/opt/harmony-smp/lib/mysql-connector-j-8.0.33.jar \
      --driver=com.mysql.cj.jdbc.Driver \
      --url=$URL \
      --username="$DBUSER" \
      --password="$DBPASSWORD" \
      --changeLogFile=/opt/harmony-smp/db/db.changelog.xml \
      update -DadminUser="$AUSER" -DadminPassword="$HASHEDPASSWORD"
  else
    echo "Schema harmony_smp already exists. Update database" >&2

    DBUSER=$(xmlstarlet sel -t -v "/Context/Resource/@username" /etc/harmony-smp/tomcat-conf/context.xml)
    DBPASSWORD=$(xmlstarlet sel -t -v "/Context/Resource/@password" /etc/harmony-smp/tomcat-conf/context.xml)

    if [[ -z $DBUSER || -z $DBPASSWORD ]]; then
      echo 'Existing database credentials not found'
      exit 1
    fi

    echo "Update database" >&2

    $LIQUIBASE_HOME/liquibase.sh \
      --classpath=/opt/harmony-smp/lib/mysql-connector-j-8.0.33.jar \
      --driver=com.mysql.cj.jdbc.Driver \
      --url=$URL \
      --username="$DBUSER" \
      --password="$DBPASSWORD" \
      --changeLogFile=/opt/harmony-smp/db/db.changelog.xml \
      update
  fi

  if [ ! -f /etc/harmony-smp/tomcat-conf/server.xml ]; then
    rm -f /etc/harmony-smp/*.p12

    KEYSTOREPASS=$(openssl rand -base64 12)
    keytool -genkeypair -keyalg RSA -alias selfsigned -keystore /etc/harmony-smp/smp-keystore.p12 -storetype PKCS12 -storepass "$KEYSTOREPASS" \
        -keypass "$KEYSTOREPASS" -validity 333 -keysize 3072 -dname "$SERVERDN" 2>/dev/null

    TRUSTSTOREPASS=$(openssl rand -base64 12)
    keytool -genkeypair -alias mock -keystore /etc/harmony-smp/smp-truststore.p12 -storetype PKCS12 -storepass "$TRUSTSTOREPASS" \
      -keypass "$TRUSTSTOREPASS" -dname "CN=mock" 2>/dev/null
    keytool -delete -alias mock -keystore /etc/harmony-smp/smp-truststore.p12 -storepass "$TRUSTSTOREPASS" 2>/dev/null

    TLSKEYPASS=$(openssl rand -base64 12)
    keytool -genkeypair -keyalg RSA -alias selfsigned -keystore /etc/harmony-smp/tls-keystore.p12 -storetype PKCS12 -storepass "$TLSKEYPASS" \
        -keypass "$TLSKEYPASS" -validity 333 -keysize 3072 -dname "$SERVERDN" 2>/dev/null

    TLSTRUSTSTOREPASS=$(openssl rand -base64 12)
    keytool -export -alias selfsigned -file /etc/harmony-smp/selfsigned.cer \
        -keystore /etc/harmony-smp/tls-keystore.p12 -storepass "$TLSKEYPASS" 2>/dev/null
    keytool -import -noprompt -alias selfsigned -file /etc/harmony-smp/selfsigned.cer \
        -keystore /etc/harmony-smp/tls-truststore.p12 -storepass "$TLSTRUSTSTOREPASS" 2>/dev/null
    rm -f /etc/harmony-smp/selfsigned.cer

    E_TLSKEYPASS=$(escape_for_sed "$TLSKEYPASS")
    E_TLSTRUSTSTOREPASS=$(escape_for_sed "$TLSTRUSTSTOREPASS")
    E_TOMCATPORT=$(escape_for_sed "$TOMCATPORT")
    sed -e "s/{{tls_keystore_password}}/$E_TLSKEYPASS/" -e "s/{{tls_truststore_password}}/$E_TLSTRUSTSTOREPASS/" \
        -e "s/{{tomcat_port}}/$E_TOMCATPORT/" \
        /opt/harmony-smp/setup/server.xml.template > /etc/harmony-smp/tomcat-conf/server.xml

    sed -e "s/{{tls_truststore_password}}/$E_TLSTRUSTSTOREPASS/" \
        /opt/harmony-smp/setup/setenv.sh.template > /opt/harmony-smp/bin/setenv.sh
    chmod +x /opt/harmony-smp/bin/setenv.sh

    E_DBUSER=$(escape_for_sed "$DBUSER")
    E_DBPASSWORD=$(escape_for_sed "$DBPASSWORD")
    sed -e "s/{{dbuser}}/$E_DBUSER/" \
        -e "s/{{dbpassword}}/$E_DBPASSWORD/" \
        /opt/harmony-smp/setup/context.xml.template > /etc/harmony-smp/tomcat-conf/context.xml

    cat >/etc/harmony-smp/smp.init.properties <<EOF
# Initial configuration

smp.keystore.filename=smp-keystore.p12
smp.keystore.password={DEC}{$KEYSTOREPASS}
smp.keystore.type=PKCS12

smp.truststore.filename=smp-truststore.p12
smp.truststore.password={DEC}{$TRUSTSTOREPASS}
smp.truststore.type=PKCS12

contextPath.output=true

bdmsl.integration.enabled=$INTEGRATESML
EOF

    if [[ $INTEGRATESML = "true" ]]; then
      cat >>/etc/harmony-smp/smp.init.properties <<EOF
bdmsl.integration.url=$SMLURL
bdmsl.integration.tls.disableCNCheck=false
bdmsl.integration.logical.address=$SMPURL
bdmsl.integration.physical.address=$SMPIP
bdmsl.integration.tls.serverSubjectRegex=
EOF
    fi
  fi
  DROPDBONERROR=false

  if [[ -n $2 ]]; then
    sed -i -E '\|^export CLASSPATH=/etc/harmony-smp.*|d' /opt/harmony-smp/bin/setenv.sh || true
  fi

  # Make sure the administrative user exists
  if ! getent passwd harmony-smp > /dev/null; then
    adduser --system --quiet --no-create-home --shell /usr/sbin/nologin --group --gecos "Harmony user" harmony-smp
  fi

  # check validity of user and group
  if [ "$(id -u harmony-smp)" -eq 0 ]; then
    echo "The Harmony SMP system user 'harmony-smp' must not have uid 0 (root).Please fix this and reinstall this package." >&2
    exit 1
  fi
  if [ "$(id -g harmony-smp)" -eq 0 ]; then
    echo "The Harmony SMP system user 'harmony-smp' must not have root as primary group. Please fix this and reinstall this package." >&2
    exit 1
  fi

  mkdir -p /opt/harmony-smp/temp

  chown -R harmony-smp:harmony-smp /opt/harmony-smp
  chmod -R u=Xrw,g=Xr,o=X /opt/harmony-smp

  # nicer log directory permissions
  mkdir -p /var/log/harmony-smp
  chmod 1770 /var/log/harmony-smp
  chown harmony-smp:adm /var/log/harmony-smp

  # config folder permissions
  chown -R harmony-smp:harmony-smp /etc/harmony-smp
  chmod -R u=Xrw,g=Xr,o=X /etc/harmony-smp

  systemctl daemon-reload
  if [ "$(systemctl is-enabled harmony-smp)" = "enabled" ]; then
    systemctl start harmony-smp 2>/dev/null || true
  fi

  SUCCESS=true
 ;;


 abort-upgrade|abort-remove|abort-deconfigure)
 ;;

 *)
    log "postinst called with unknown argument \`$1'" >&2
    exit 1
 ;;
esac

exit 0
