#!/command/with-contenv bash
set -euo pipefail

readonly STAGE="init-environment"

log() {
  local level="$1"
  local message="$2"

  harmony-log "$level" "$STAGE" "$message"
}

get_property() {
  local cfg_path="$1"
  local property="$2"
  local default_value="$3"

  harmony-property -s "$STAGE" -a GET -c "$cfg_path" -p "$property" -v "$default_value" --allow-missing-paths
}

log "DEBUG" "Started"

HARMONY_VERSION="${HARMONY_VERSION:-UNDEFINED}"

log "INFO" "Starting Harmony Access Point version $HARMONY_VERSION"
log "INFO" "    User UID: $(id -u)"
log "INFO" "    User GID: $(id -g)"

# -------------------------------
# Load parameters from file (if defined)
# -------------------------------
if [[ -n "${HARMONY_PARAM_FILE:-}" && -f "$HARMONY_PARAM_FILE" ]]; then
  log "INFO" "Reading parameters from $HARMONY_PARAM_FILE..."
  while IFS='=' read -r key value; do
    # Ignore comments, empty keys, already defined variables, or empty values
    [[ "$key" =~ ^#.*$ || -z "$key" || -n "${!key:-}" || -z "$value" ]] && continue
    declare "$key=$value"
    printf "%s" "$value" > "/var/run/s6/container_environment/$key"
  done < "$HARMONY_PARAM_FILE"
fi

# -------------------------------
# Set default directories
# -------------------------------
harmony_base="${HARMONY_BASE:-/var/opt/harmony-ap}" # Runtime state
harmony_home="${HARMONY_HOME:-/opt/harmony-ap}"     # Static and read-only
temp_dir="${TEMP_DIR:-/tmp/harmony-ap}"
catalina_temp_dir="${CATALINA_TEMP_DIR:-/var/tmp/harmony-ap}"

printf "%s" "$harmony_base" > /var/run/s6/container_environment/HARMONY_BASE
printf "%s" "$harmony_home" > /var/run/s6/container_environment/HARMONY_HOME
printf "%s" "$temp_dir" > /var/run/s6/container_environment/TEMP_DIR
printf "%s" "$catalina_temp_dir" > /var/run/s6/container_environment/CATALINA_TEMP_DIR

# -------------------------------
# Set config file paths
# -------------------------------
config_path="${CONFIG_PATH:-${harmony_base}/etc/domibus.properties}"
temp_config_path="${temp_dir}/domibus.properties"

printf "%s" "$config_path" > /var/run/s6/container_environment/CONFIG_PATH
printf "%s" "$temp_config_path" > /var/run/s6/container_environment/TEMP_CONFIG_PATH

# -------------------------------
# Set common Harmony AP properties
# -------------------------------
party_name="${PARTY_NAME:-$(get_property "$config_path" 'domibus.security.key.private.alias' 'selfsigned')}"
deployment_clustered="${DEPLOYMENT_CLUSTERED:-$(get_property "$config_path" 'domibus.deployment.clustered' 'false')}"

printf "%s" "$party_name" > /var/run/s6/container_environment/PARTY_NAME
printf "%s" "$deployment_clustered" > /var/run/s6/container_environment/DEPLOYMENT_CLUSTERED

log "DEBUG" "Done"