#!/command/with-contenv bash
set -euo pipefail

# shellcheck disable=SC2034 # Used in sourced scripts
readonly STAGE="svc-monitor"

source /usr/lib/harmony-ap/lib/harmony-common
source /usr/lib/harmony-ap/lib/harmony-cluster

if [[ "$DEPLOYMENT_CLUSTERED" != "true" || "$CLUSTER_BACKEND" == "none" ]]; then
  log DEBUG "Clustering disabled or not using a cluster backend; exiting svc-monitor"
  s6-svc -d /run/service/svc-monitor
  exit 0
fi

while true; do
  if is_primary; then
    renew_lease
  else
    if acquire_primary; then
      log INFO "Node promoted to primary (failover successful)"

      if [[ "${REPLICA_STATE:-}" == "ready" ]]; then
        set_ready_flag
      fi
    fi
  fi
  sleep $(( RANDOM % 11 + 30 )) # Sleep for a random duration between 30 and 40 seconds
done
