-- liquibase formatted sql

-- changeset root:1670093596804-1 contextFilter:legacy
CREATE TABLE SMP_CERTIFICATE (ID BIGINT NOT NULL COMMENT 'Shared primary key with master table SMP_USER', CERTIFICATE_ID VARCHAR(1024) NULL COMMENT 'Formatted Certificate id using tags: cn, o, c:serialNumber', CREATED_ON datetime NOT NULL, CRL_URL VARCHAR(4000) NULL COMMENT 'URL to the certificate revocation list (CRL)', ISSUER VARCHAR(1024) NULL COMMENT 'Certificate issuer (canonical form)', LAST_UPDATED_ON datetime NOT NULL, PEM_ENCODED_CERT LONGTEXT NULL COMMENT 'PEM encoded  certificate', SERIALNUMBER VARCHAR(128) NULL COMMENT 'Certificate serial number', SUBJECT VARCHAR(1024) NULL COMMENT 'Certificate subject (canonical form)', VALID_FROM datetime NULL COMMENT 'Certificate valid from date.', VALID_TO datetime NULL COMMENT 'Certificate valid to date.', CONSTRAINT PK_SMP_CERTIFICATE PRIMARY KEY (ID), UNIQUE (CERTIFICATE_ID)) COMMENT='SMP user certificates';

-- changeset root:1670093596804-2 contextFilter:legacy
CREATE TABLE SMP_CERTIFICATE_AUD (ID BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE TINYINT(3) NULL, CERTIFICATE_ID VARCHAR(1024) NULL, CREATED_ON datetime NULL, CRL_URL VARCHAR(4000) NULL, ISSUER VARCHAR(1024) NULL, LAST_UPDATED_ON datetime NULL, PEM_ENCODED_CERT LONGTEXT NULL, SERIALNUMBER VARCHAR(128) NULL, SUBJECT VARCHAR(1024) NULL, VALID_FROM datetime NULL, VALID_TO datetime NULL, CONSTRAINT PK_SMP_CERTIFICATE_AUD PRIMARY KEY (ID, REV));

-- changeset root:1670093596804-3 contextFilter:legacy
CREATE TABLE SMP_CONFIGURATION (PROPERTY VARCHAR(512) NOT NULL COMMENT 'Property name/key', CREATED_ON datetime NOT NULL COMMENT 'Row inserted on date', `DESCRIPTION` VARCHAR(4000) NULL COMMENT 'Property description', LAST_UPDATED_ON datetime NOT NULL COMMENT 'Row modified on date', VALUE VARCHAR(4000) NULL COMMENT 'Property value', CONSTRAINT PK_SMP_CONFIGURATION PRIMARY KEY (PROPERTY)) COMMENT='SMP user certificates';

-- changeset root:1670093596804-4 contextFilter:legacy
CREATE TABLE SMP_DOMAIN (ID BIGINT NOT NULL COMMENT 'Unique domain id', CREATED_ON datetime NOT NULL, DOMAIN_CODE VARCHAR(256) NOT NULL COMMENT 'Domain code used as http parameter in rest webservices', LAST_UPDATED_ON datetime NOT NULL, SIGNATURE_KEY_ALIAS VARCHAR(256) NULL COMMENT 'Signature key alias used for SML integration', SML_BLUE_COAT_AUTH BIT(1) NOT NULL COMMENT 'Flag for SML authentication type - use CLientCert header or  HTTPS ClientCertificate (key)', SML_CLIENT_CERT_HEADER VARCHAR(4000) NULL COMMENT 'Client-Cert header used behind RP - BlueCoat for SML integration', SML_CLIENT_KEY_ALIAS VARCHAR(256) NULL COMMENT 'Client key alias used for SML integration', SML_PARTC_IDENT_REGEXP VARCHAR(4000) NULL COMMENT 'Reqular expresion for participant ids', SML_REGISTERED BIT(1) NOT NULL COMMENT 'Flag for: Is domain registered in SML', SML_SMP_ID VARCHAR(256) NULL COMMENT 'SMP ID used for SML integration', SML_SUBDOMAIN VARCHAR(256) NULL COMMENT 'SML subdomain', CONSTRAINT PK_SMP_DOMAIN PRIMARY KEY (ID), UNIQUE (DOMAIN_CODE), UNIQUE (SML_SUBDOMAIN)) COMMENT='SMP can handle multiple domains. This table contains domain specific data';

-- changeset root:1670093596804-5 contextFilter:legacy
CREATE TABLE SMP_DOMAIN_AUD (ID BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE TINYINT(3) NULL, CREATED_ON datetime NULL, DOMAIN_CODE VARCHAR(256) NULL, LAST_UPDATED_ON datetime NULL, SIGNATURE_KEY_ALIAS VARCHAR(256) NULL, SML_BLUE_COAT_AUTH BIT(1) NULL, SML_CLIENT_CERT_HEADER VARCHAR(4000) NULL, SML_CLIENT_KEY_ALIAS VARCHAR(256) NULL, SML_PARTC_IDENT_REGEXP VARCHAR(4000) NULL, SML_REGISTERED BIT(1) NULL, SML_SMP_ID VARCHAR(256) NULL, SML_SUBDOMAIN VARCHAR(256) NULL, CONSTRAINT PK_SMP_DOMAIN_AUD PRIMARY KEY (ID, REV));

-- changeset root:1670093596804-6 contextFilter:legacy
CREATE TABLE SMP_DOMAIN_SEQ (next_val BIGINT NULL);

-- changeset root:1670093596804-7 contextFilter:legacy
CREATE TABLE SMP_OWNERSHIP (FK_SG_ID BIGINT NOT NULL, FK_USER_ID BIGINT NOT NULL, CONSTRAINT PK_SMP_OWNERSHIP PRIMARY KEY (FK_SG_ID, FK_USER_ID));

-- changeset root:1670093596804-8 contextFilter:legacy
CREATE TABLE SMP_OWNERSHIP_AUD (REV BIGINT NOT NULL, FK_SG_ID BIGINT NOT NULL, FK_USER_ID BIGINT NOT NULL, REVTYPE TINYINT(3) NULL, CONSTRAINT PK_SMP_OWNERSHIP_AUD PRIMARY KEY (REV, FK_SG_ID, FK_USER_ID));

-- changeset root:1670093596804-9 contextFilter:legacy
CREATE TABLE SMP_REVISION_SEQ (next_val BIGINT NULL);

-- changeset root:1670093596804-10 contextFilter:legacy
CREATE TABLE SMP_REV_INFO (id BIGINT NOT NULL, REVISION_DATE datetime NULL, timestamp BIGINT NOT NULL, USERNAME VARCHAR(255) NULL, CONSTRAINT PK_SMP_REV_INFO PRIMARY KEY (id));

-- changeset root:1670093596804-11 contextFilter:legacy
CREATE TABLE SMP_SERVICE_GROUP (ID BIGINT NOT NULL COMMENT 'Unique Servicegroup id', CREATED_ON datetime NOT NULL, LAST_UPDATED_ON datetime NOT NULL, PARTICIPANT_IDENTIFIER VARCHAR(256) NOT NULL, PARTICIPANT_SCHEME VARCHAR(256) NOT NULL, CONSTRAINT PK_SMP_SERVICE_GROUP PRIMARY KEY (ID)) COMMENT='Service group data - Identifier and scheme';

-- changeset root:1670093596804-12 contextFilter:legacy
CREATE TABLE SMP_SERVICE_GROUP_AUD (ID BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE TINYINT(3) NULL, CREATED_ON datetime NULL, LAST_UPDATED_ON datetime NULL, PARTICIPANT_IDENTIFIER VARCHAR(256) NULL, PARTICIPANT_SCHEME VARCHAR(256) NULL, CONSTRAINT PK_SMP_SERVICE_GROUP_AUD PRIMARY KEY (ID, REV));

-- changeset root:1670093596804-13 contextFilter:legacy
CREATE TABLE SMP_SERVICE_GROUP_DOMAIN (ID BIGINT NOT NULL, CREATED_ON datetime NOT NULL, LAST_UPDATED_ON datetime NOT NULL, SML_REGISTERED BIT(1) NOT NULL, FK_DOMAIN_ID BIGINT NULL, FK_SG_ID BIGINT NULL, CONSTRAINT PK_SMP_SERVICE_GROUP_DOMAIN PRIMARY KEY (ID));

-- changeset root:1670093596804-14 contextFilter:legacy
CREATE TABLE SMP_SERVICE_GROUP_DOMAIN_AUD (ID BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE TINYINT(3) NULL, CREATED_ON datetime NULL, LAST_UPDATED_ON datetime NULL, SML_REGISTERED BIT(1) NULL, FK_DOMAIN_ID BIGINT NULL, FK_SG_ID BIGINT NULL, CONSTRAINT PK_SMP_SERVICE_GROUP_DOMAIN_AUD PRIMARY KEY (ID, REV));

-- changeset root:1670093596804-15 contextFilter:legacy
CREATE TABLE SMP_SERVICE_GROUP_DOMAIN_SEQ (next_val BIGINT NULL);

-- changeset root:1670093596804-16 contextFilter:legacy
CREATE TABLE SMP_SERVICE_GROUP_SEQ (next_val BIGINT NULL);

-- changeset root:1670093596804-17 contextFilter:legacy
CREATE TABLE SMP_SERVICE_METADATA (ID BIGINT NOT NULL COMMENT 'Shared primary key with master table SMP_SERVICE_METADATA', CREATED_ON datetime NOT NULL, DOCUMENT_IDENTIFIER VARCHAR(500) NOT NULL, DOCUMENT_SCHEME VARCHAR(500) NULL, LAST_UPDATED_ON datetime NOT NULL, FK_SG_DOM_ID BIGINT NOT NULL, CONSTRAINT PK_SMP_SERVICE_METADATA PRIMARY KEY (ID)) COMMENT='Service metadata';

-- changeset root:1670093596804-18 contextFilter:legacy
CREATE TABLE SMP_SERVICE_METADATA_AUD (ID BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE TINYINT(3) NULL, CREATED_ON datetime NULL, DOCUMENT_IDENTIFIER VARCHAR(500) NULL, DOCUMENT_SCHEME VARCHAR(500) NULL, LAST_UPDATED_ON datetime NULL, FK_SG_DOM_ID BIGINT NULL, CONSTRAINT PK_SMP_SERVICE_METADATA_AUD PRIMARY KEY (ID, REV));

-- changeset root:1670093596804-19 contextFilter:legacy
CREATE TABLE SMP_SERVICE_METADATA_SEQ (next_val BIGINT NULL);

-- changeset root:1670093596804-20 contextFilter:legacy
CREATE TABLE SMP_SERVICE_METADATA_XML (ID BIGINT NOT NULL, CREATED_ON datetime NOT NULL, LAST_UPDATED_ON datetime NOT NULL, XML_CONTENT LONGBLOB NULL COMMENT 'XML service metadata', CONSTRAINT PK_SMP_SERVICE_METADATA_XML PRIMARY KEY (ID)) COMMENT='Service group metadata xml blob';

-- changeset root:1670093596804-21 contextFilter:legacy
CREATE TABLE SMP_SERVICE_METADATA_XML_AUD (ID BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE TINYINT(3) NULL, CREATED_ON datetime NULL, LAST_UPDATED_ON datetime NULL, XML_CONTENT LONGBLOB NULL, CONSTRAINT PK_SMP_SERVICE_METADATA_XML_AUD PRIMARY KEY (ID, REV));

-- changeset root:1670093596804-22 contextFilter:legacy
CREATE TABLE SMP_SG_EXTENSION (ID BIGINT NOT NULL, CREATED_ON datetime NOT NULL, EXTENSION LONGBLOB NULL COMMENT 'XML extension(s) for servicegroup', LAST_UPDATED_ON datetime NOT NULL, CONSTRAINT PK_SMP_SG_EXTENSION PRIMARY KEY (ID)) COMMENT='Service group extension blob';

-- changeset root:1670093596804-23 contextFilter:legacy
CREATE TABLE SMP_SG_EXTENSION_AUD (ID BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE TINYINT(3) NULL, CREATED_ON datetime NULL, EXTENSION LONGBLOB NULL, LAST_UPDATED_ON datetime NULL, CONSTRAINT PK_SMP_SG_EXTENSION_AUD PRIMARY KEY (ID, REV));

-- changeset root:1670093596804-24 contextFilter:legacy
CREATE TABLE SMP_USER (ID BIGINT NOT NULL COMMENT 'Unique user id', ACTIVE BIT(1) NOT NULL COMMENT 'Is user active', CREATED_ON datetime NOT NULL, EMAIL VARCHAR(256) NULL COMMENT 'User email', LAST_UPDATED_ON datetime NOT NULL, PASSWORD VARCHAR(256) NULL COMMENT 'BCrypted password for username/password login', PASSWORD_CHANGED datetime NULL COMMENT 'Last date when password was changed', `ROLE` VARCHAR(256) NULL COMMENT 'User role', USERNAME VARCHAR(256) NULL COMMENT 'Login username', CONSTRAINT PK_SMP_USER PRIMARY KEY (ID), UNIQUE (USERNAME)) COMMENT='SMP can handle multiple domains. This table contains domain specific data';

-- changeset root:1670093596804-25 contextFilter:legacy
CREATE TABLE SMP_USER_AUD (ID BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE TINYINT(3) NULL, ACTIVE BIT(1) NULL, CREATED_ON datetime NULL, EMAIL VARCHAR(256) NULL, LAST_UPDATED_ON datetime NULL, PASSWORD VARCHAR(256) NULL, PASSWORD_CHANGED datetime NULL, `ROLE` VARCHAR(256) NULL, USERNAME VARCHAR(256) NULL, CONSTRAINT PK_SMP_USER_AUD PRIMARY KEY (ID, REV));

-- changeset root:1670093596804-26 contextFilter:legacy
CREATE TABLE SMP_USER_SEQ (next_val BIGINT NULL);

-- changeset root:1670093596804-27 contextFilter:legacy
ALTER TABLE SMP_SERVICE_METADATA ADD CONSTRAINT SMP_MT_UNIQ_SG_DOC_IDX UNIQUE (FK_SG_DOM_ID, DOCUMENT_IDENTIFIER, DOCUMENT_SCHEME);

-- changeset root:1670093596804-28 contextFilter:legacy
ALTER TABLE SMP_SERVICE_GROUP ADD CONSTRAINT SMP_SG_UNIQ_PARTC_IDX UNIQUE (PARTICIPANT_SCHEME, PARTICIPANT_IDENTIFIER);

-- changeset root:1670093596804-29 contextFilter:legacy
CREATE INDEX FK2786r5minnkai3d22b191iiiq ON SMP_USER_AUD(REV);

-- changeset root:1670093596804-30 contextFilter:legacy
CREATE INDEX FK35qm8xmi74kfenugeonijodsg ON SMP_DOMAIN_AUD(REV);

-- changeset root:1670093596804-31 contextFilter:legacy
CREATE INDEX FK6uc9r0eqw16baooxtmqjkih0j ON SMP_SERVICE_GROUP_DOMAIN_AUD(REV);

-- changeset root:1670093596804-32 contextFilter:legacy
CREATE INDEX FKbqr9pdnik1qxx2hi0xn4n7f61 ON SMP_SERVICE_METADATA_AUD(REV);

-- changeset root:1670093596804-33 contextFilter:legacy
CREATE INDEX FKevatmlvvwoxfnjxkvmokkencb ON SMP_SERVICE_METADATA_XML_AUD(REV);

-- changeset root:1670093596804-34 contextFilter:legacy
CREATE INDEX FKgcvhnk2n34d3c6jhni5l3s3x3 ON SMP_SERVICE_GROUP_DOMAIN(FK_SG_ID);

-- changeset root:1670093596804-35 contextFilter:legacy
CREATE INDEX FKj3caimhegwyav1scpwrxoslef ON SMP_SERVICE_GROUP_AUD(REV);

-- changeset root:1670093596804-36 contextFilter:legacy
CREATE INDEX FKmdo9v2422adwyebvl34qa3ap6 ON SMP_SG_EXTENSION_AUD(REV);

-- changeset root:1670093596804-37 contextFilter:legacy
CREATE INDEX FKnrwm8en8vv10li8ihwnurwd9e ON SMP_CERTIFICATE_AUD(REV);

-- changeset root:1670093596804-38 contextFilter:legacy
CREATE INDEX FKo186xtefda6avl5p1tuqchp3n ON SMP_SERVICE_GROUP_DOMAIN(FK_DOMAIN_ID);

-- changeset root:1670093596804-39 contextFilter:legacy
CREATE INDEX FKrnqwq06lbfwciup4rj8nvjpmy ON SMP_OWNERSHIP(FK_USER_ID);

-- changeset root:1670093596804-40 contextFilter:legacy
CREATE INDEX SMP_SG_PART_ID_IDX ON SMP_SERVICE_GROUP(PARTICIPANT_IDENTIFIER);

-- changeset root:1670093596804-41 contextFilter:legacy
CREATE INDEX SMP_SG_PART_SCH_IDX ON SMP_SERVICE_GROUP(PARTICIPANT_SCHEME);

-- changeset root:1670093596804-42 contextFilter:legacy
CREATE INDEX SMP_SMD_DOC_ID_IDX ON SMP_SERVICE_METADATA(DOCUMENT_IDENTIFIER);

-- changeset root:1670093596804-43 contextFilter:legacy
CREATE INDEX SMP_SMD_DOC_SCH_IDX ON SMP_SERVICE_METADATA(DOCUMENT_SCHEME);

-- changeset root:1670093596804-44 contextFilter:legacy
ALTER TABLE SMP_OWNERSHIP_AUD ADD CONSTRAINT FK1lqynlbk8ow1ouxetf5wybk3k FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (id) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:1670093596804-45 contextFilter:legacy
ALTER TABLE SMP_USER_AUD ADD CONSTRAINT FK2786r5minnkai3d22b191iiiq FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (id) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:1670093596804-46 contextFilter:legacy
ALTER TABLE SMP_DOMAIN_AUD ADD CONSTRAINT FK35qm8xmi74kfenugeonijodsg FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (id) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:1670093596804-47 contextFilter:legacy
ALTER TABLE SMP_SERVICE_METADATA_XML ADD CONSTRAINT FK4b1x06xlavcgbjnuilgksi7nm FOREIGN KEY (ID) REFERENCES SMP_SERVICE_METADATA (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:1670093596804-48 contextFilter:legacy
ALTER TABLE SMP_SERVICE_GROUP_DOMAIN_AUD ADD CONSTRAINT FK6uc9r0eqw16baooxtmqjkih0j FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (id) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:1670093596804-49 contextFilter:legacy
ALTER TABLE SMP_CERTIFICATE ADD CONSTRAINT FKayqgpj5ot3o8vrpduul7sstta FOREIGN KEY (ID) REFERENCES SMP_USER (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:1670093596804-50 contextFilter:legacy
ALTER TABLE SMP_SERVICE_METADATA_AUD ADD CONSTRAINT FKbqr9pdnik1qxx2hi0xn4n7f61 FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (id) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:1670093596804-51 contextFilter:legacy
ALTER TABLE SMP_SERVICE_METADATA_XML_AUD ADD CONSTRAINT FKevatmlvvwoxfnjxkvmokkencb FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (id) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:1670093596804-52 contextFilter:legacy
ALTER TABLE SMP_SERVICE_METADATA ADD CONSTRAINT FKfvcml6b8x7kn80m30h8pxs7jl FOREIGN KEY (FK_SG_DOM_ID) REFERENCES SMP_SERVICE_GROUP_DOMAIN (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:1670093596804-53 contextFilter:legacy
ALTER TABLE SMP_SERVICE_GROUP_DOMAIN ADD CONSTRAINT FKgcvhnk2n34d3c6jhni5l3s3x3 FOREIGN KEY (FK_SG_ID) REFERENCES SMP_SERVICE_GROUP (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:1670093596804-54 contextFilter:legacy
ALTER TABLE SMP_OWNERSHIP ADD CONSTRAINT FKgexq5n6ftsid8ehqljvjh8p4i FOREIGN KEY (FK_SG_ID) REFERENCES SMP_SERVICE_GROUP (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:1670093596804-55 contextFilter:legacy
ALTER TABLE SMP_SERVICE_GROUP_AUD ADD CONSTRAINT FKj3caimhegwyav1scpwrxoslef FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (id) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:1670093596804-56 contextFilter:legacy
ALTER TABLE SMP_SG_EXTENSION_AUD ADD CONSTRAINT FKmdo9v2422adwyebvl34qa3ap6 FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (id) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:1670093596804-57 contextFilter:legacy
ALTER TABLE SMP_CERTIFICATE_AUD ADD CONSTRAINT FKnrwm8en8vv10li8ihwnurwd9e FOREIGN KEY (REV) REFERENCES SMP_REV_INFO (id) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:1670093596804-58 contextFilter:legacy
ALTER TABLE SMP_SERVICE_GROUP_DOMAIN ADD CONSTRAINT FKo186xtefda6avl5p1tuqchp3n FOREIGN KEY (FK_DOMAIN_ID) REFERENCES SMP_DOMAIN (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:1670093596804-59 contextFilter:legacy
ALTER TABLE SMP_OWNERSHIP ADD CONSTRAINT FKrnqwq06lbfwciup4rj8nvjpmy FOREIGN KEY (FK_USER_ID) REFERENCES SMP_USER (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset root:1670093596804-60 contextFilter:legacy
ALTER TABLE SMP_SG_EXTENSION ADD CONSTRAINT FKtf0mfonugp2jbkqo2o142chib FOREIGN KEY (ID) REFERENCES SMP_SERVICE_GROUP (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;


-- changeset 4_1_1_to_4_2:1670093596804-61 contextFilter:2_version
UPDATE SMP_USER set USERNAME ='USERNAME_' | SMP_USER.ID  where USERNAME IS NULL;
commit;

create table SMP_ALERT (
   ID bigint not null auto_increment comment 'Unique alert id',
    CREATED_ON datetime not null,
    LAST_UPDATED_ON datetime not null,
    ALERT_LEVEL varchar(255)  CHARACTER SET utf8 COLLATE utf8_bin,
    ALERT_STATUS varchar(255)  CHARACTER SET utf8 COLLATE utf8_bin,
    ALERT_STATUS_DESC varchar(1024)  CHARACTER SET utf8 COLLATE utf8_bin,
    ALERT_TYPE varchar(255)  CHARACTER SET utf8 COLLATE utf8_bin,
    MAIL_SUBJECT varchar(1024)  CHARACTER SET utf8 COLLATE utf8_bin,
    MAIL_TO varchar(1024)  CHARACTER SET utf8 COLLATE utf8_bin,
    PROCESSED_TIME datetime,
    REPORTING_TIME datetime,
    FOR_USERNAME varchar(256)  CHARACTER SET utf8 COLLATE utf8_bin,
    primary key (ID)
) comment='SMP alerts' ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table SMP_ALERT_AUD (
   ID bigint not null,
    REV bigint not null,
    REVTYPE tinyint,
    CREATED_ON datetime,
    LAST_UPDATED_ON datetime,
    ALERT_LEVEL varchar(255)  CHARACTER SET utf8 COLLATE utf8_bin,
    ALERT_STATUS varchar(255)  CHARACTER SET utf8 COLLATE utf8_bin,
    ALERT_STATUS_DESC varchar(1024)  CHARACTER SET utf8 COLLATE utf8_bin,
    ALERT_TYPE varchar(255)  CHARACTER SET utf8 COLLATE utf8_bin,
    MAIL_SUBJECT varchar(1024)  CHARACTER SET utf8 COLLATE utf8_bin,
    MAIL_TO varchar(1024)  CHARACTER SET utf8 COLLATE utf8_bin,
    PROCESSED_TIME datetime,
    REPORTING_TIME datetime,
    FOR_USERNAME varchar(256)  CHARACTER SET utf8 COLLATE utf8_bin,
    primary key (ID, REV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table SMP_ALERT_PROPERTY (
   ID bigint not null auto_increment comment 'Unique alert property id',
    CREATED_ON datetime not null,
    LAST_UPDATED_ON datetime not null,
    PROPERTY varchar(255)  CHARACTER SET utf8 COLLATE utf8_bin,
    VALUE varchar(1024)  CHARACTER SET utf8 COLLATE utf8_bin,
    FK_ALERT_ID bigint,
    primary key (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table SMP_ALERT_PROPERTY_AUD (
   ID bigint not null,
    REV bigint not null,
    REVTYPE tinyint,
    CREATED_ON datetime,
    LAST_UPDATED_ON datetime,
    PROPERTY varchar(255)  CHARACTER SET utf8 COLLATE utf8_bin,
    VALUE varchar(1024)  CHARACTER SET utf8 COLLATE utf8_bin,
    FK_ALERT_ID bigint,
    primary key (ID, REV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE SMP_CERTIFICATE ADD EXPIRE_LAST_ALERT_ON datetime comment 'Generated last expire alert';
ALTER TABLE SMP_CERTIFICATE_AUD ADD EXPIRE_LAST_ALERT_ON datetime comment 'Generated last expire alert';

create table SMP_CONFIGURATION_AUD (
   PROPERTY varchar(512)  CHARACTER SET utf8 COLLATE utf8_bin not null,
    REV bigint not null,
    REVTYPE tinyint,
    CREATED_ON datetime,
    LAST_UPDATED_ON datetime,
    DESCRIPTION varchar(4000)  CHARACTER SET utf8 COLLATE utf8_bin,
    VALUE varchar(4000)  CHARACTER SET utf8 COLLATE utf8_bin,
    primary key (PROPERTY, REV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE SMP_USER MODIFY USERNAME varchar(256)  CHARACTER SET utf8 COLLATE utf8_bin not null comment 'Unique username identifier. The Username must not be null';

ALTER TABLE SMP_USER ADD ACCESS_TOKEN varchar(256)  CHARACTER SET utf8 COLLATE utf8_bin comment 'BCrypted personal access token';
ALTER TABLE SMP_USER ADD ACCESS_TOKEN_LAST_ALERT_ON datetime comment 'Generated last access token expire alert';
ALTER TABLE SMP_USER ADD ACCESS_TOKEN_EXPIRE_ON datetime comment 'Date when personal access token will expire';
ALTER TABLE SMP_USER ADD ACCESS_TOKEN_GENERATED_ON datetime comment 'Date when personal access token was generated';
ALTER TABLE SMP_USER ADD ACCESS_TOKEN_ID varchar(256)  CHARACTER SET utf8 COLLATE utf8_bin comment 'Personal access token id';
ALTER TABLE SMP_USER ADD LAST_FAILED_LOGIN_ON datetime comment 'Last failed login attempt';
ALTER TABLE SMP_USER ADD AT_LAST_FAILED_LOGIN_ON datetime comment 'Last failed token login attempt';
ALTER TABLE SMP_USER ADD PASSWORD_LAST_ALERT_ON datetime comment 'Generated last password expire alert';
ALTER TABLE SMP_USER ADD PASSWORD_EXPIRE_ON datetime comment 'Date when password will expire';
ALTER TABLE SMP_USER ADD LOGIN_FAILURE_COUNT integer comment 'Sequential login failure count';
ALTER TABLE SMP_USER ADD AT_LOGIN_FAILURE_COUNT integer comment 'Sequential token login failure count';

ALTER TABLE SMP_USER_AUD ADD ACCESS_TOKEN varchar(256)  CHARACTER SET utf8 COLLATE utf8_bin comment 'BCrypted personal access token';
ALTER TABLE SMP_USER_AUD ADD ACCESS_TOKEN_LAST_ALERT_ON datetime comment 'Generated last access token expire alert';
ALTER TABLE SMP_USER_AUD ADD ACCESS_TOKEN_EXPIRE_ON datetime comment 'Date when personal access token will expire';
ALTER TABLE SMP_USER_AUD ADD ACCESS_TOKEN_GENERATED_ON datetime comment 'Date when personal access token was generated';
ALTER TABLE SMP_USER_AUD ADD ACCESS_TOKEN_ID varchar(256)  CHARACTER SET utf8 COLLATE utf8_bin comment 'Personal access token id';
ALTER TABLE SMP_USER_AUD ADD LAST_FAILED_LOGIN_ON datetime comment 'Last failed login attempt';
ALTER TABLE SMP_USER_AUD ADD AT_LAST_FAILED_LOGIN_ON datetime comment 'Last failed token login attempt';
ALTER TABLE SMP_USER_AUD ADD PASSWORD_LAST_ALERT_ON datetime comment 'Generated last password expire alert';
ALTER TABLE SMP_USER_AUD ADD PASSWORD_EXPIRE_ON datetime comment 'Date when password will expire';
ALTER TABLE SMP_USER_AUD ADD LOGIN_FAILURE_COUNT integer comment 'Sequential login failure count';
ALTER TABLE SMP_USER_AUD ADD AT_LOGIN_FAILURE_COUNT integer comment 'Sequential token login failure count';

alter table SMP_USER
   add constraint UK_tk9bjsmd2mevgt3b997i6pl27 unique (ACCESS_TOKEN_ID);
   alter table SMP_ALERT_AUD
   add constraint FKrw0qnto448ojlirpfmfntd8v2
   foreign key (REV)
   references SMP_REV_INFO (id);

alter table SMP_ALERT_PROPERTY
   add constraint FK15r37w3r5ty5f6074ykr2o4i6
   foreign key (FK_ALERT_ID)
   references SMP_ALERT (ID);

alter table SMP_ALERT_PROPERTY_AUD
   add constraint FKod33qjx87ih1a0skxl2sgddar
   foreign key (REV)
   references SMP_REV_INFO (id);

alter table SMP_CONFIGURATION_AUD
   add constraint FKd4yhbdlusovfbdti1fjkuxp9m
   foreign key (REV)
   references SMP_REV_INFO (id);

SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE SMP_REV_INFO MODIFY COLUMN id bigint not null auto_increment;
ALTER TABLE SMP_SERVICE_GROUP MODIFY COLUMN ID bigint not null auto_increment comment 'Unique ServiceGroup id';
ALTER TABLE SMP_SERVICE_GROUP_DOMAIN MODIFY COLUMN ID bigint not null auto_increment;
ALTER TABLE SMP_SERVICE_METADATA MODIFY COLUMN ID bigint not null auto_increment comment 'Shared primary key with master table SMP_SERVICE_METADATA';
ALTER TABLE SMP_USER MODIFY COLUMN ID bigint not null auto_increment comment 'Unique user id';
SET FOREIGN_KEY_CHECKS = 1;

-- drop sequence tables , because the are not needed anymore!
drop table SMP_DOMAIN_SEQ;
drop table SMP_REVISION_SEQ;
drop table SMP_SERVICE_GROUP_DOMAIN_SEQ;
drop table SMP_SERVICE_GROUP_SEQ;
drop table SMP_SERVICE_METADATA_SEQ;
drop table SMP_USER_SEQ;
-- set init back-compatible credentials to access tokens
UPDATE SMP_USER set ACCESS_TOKEN_ID = SMP_USER.USERNAME, ACCESS_TOKEN=SMP_USER.PASSWORD;
commit;
