# **************************************************************************
# Database connection can be achieved using custom datasource configuration
# or reusing application server datasource.
# **************************************************************************
## set database hibernate dialect
#smp.jdbc.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# *********************************
#  Custom defined datasource
# *********************************
# mysql database example. Please replace the values with your database configuration and if possible use datasource JNDI configuration
# to avoid exposing the database credentials in the configuration file. Please see the documentation on how to configure tomcat
# to use JNDI
# tomcat datasource JNDI example
# smp.datasource.jndi = java:comp/env/jdbc/harmony-smp

# *********************************
# db configuration alternative
#smp.jdbc.driver=com.mysql.cj.jdbc.Driver
#smp.jdbc.url=jdbc:mysql://localhost:3306/harmony_smp
#smp.jdbc.user=[username]
#smp.jdbc.password=[password]

# *********************************
# security folder
# *********************************
# smp.security.folder=./smp/

# *********************************
# Logging properties
# *********************************
# smp log folder
# smp.log.folder=../logs/

# custom logback configuration file
# smp.log.configuration.file=smp-logback.xml

# *********************************
# Extension folder
# *********************************
# path where SMP extensions are located. The Folder is loaded by the SMP classloader at startup.
# smp.libraries.folder=./ext-lib


# *********************************
# Locale folder
# *********************************
# The locale folder contains the translations for the SMP web application.
# smp.locale.folder=./locales
