#!/bin/bash
if [[ "$1" = "configure" && -n "$2" ]]; then
  MIN_VERSION="1.4.0"
  if dpkg --compare-versions "$MIN_VERSION" gt "$2"; then
    echo "harmony-ap: ERROR: Upgrade from version $2 not supported." >&2
    exit 1
  fi
fi

get_prop() {
  local prop="$1";
  grep -m1 -Po "^${prop}\s*=\s*\K.*$" /etc/harmony-ap/domibus.properties 2>/dev/null || echo ""
}

. /usr/share/debconf/confmodule

if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ]; then

  db_beginblock
  db_input high harmony-ap/adminuser || true
  db_input high harmony-ap/adminpassword || true
  db_endblock
  db_go

  USEDYNAMIC="$(get_prop domibus.dynamicdiscovery.useDynamicDiscovery)"
  if [[ -n "$USEDYNAMIC" ]]; then
    db_set harmony-ap/usedynamicdiscovery "$USEDYNAMIC"
  fi
  db_input high harmony-ap/usedynamicdiscovery
  db_go

  db_get harmony-ap/usedynamicdiscovery
  USEDYNAMIC="${RET}"

  SML_ZONE="$(get_prop domibus.smlzone)"
  if [[ -n "$SML_ZONE" ]]; then
    db_set harmony-ap/smlzone "$SML_ZONE"
  fi
  if [ "$USEDYNAMIC" = true ]; then
    db_input high harmony-ap/smlzone
    db_go
  fi

  db_input high harmony-ap/partyname || true
  db_go
  db_get harmony-ap/partyname
  PARTY_NAME=$RET

  if [[ ! -f /etc/harmony-ap/ap-keystore.jks && ! -f /etc/harmony-ap/ap-keystore.p12 ]]; then
    db_get harmony-ap/securitydn
    if [[ -z $RET ]]; then
      db_set harmony-ap/securitydn "CN=$PARTY_NAME"
    fi
    db_input high harmony-ap/securitydn || true
    db_go
  fi

  if [[ ! -f /etc/harmony-ap/tls-keystore.jks && ! -f /etc/harmony-ap/tls-keystore.p12 ]]; then
    db_get harmony-ap/serverdn
    if [[ -z $RET ]]; then
      db_set harmony-ap/serverdn "CN=$(hostname -f)"
    fi
    db_input high harmony-ap/serverdn || true
    db_go

    db_get harmony-ap/serversan
    if [[ -z $RET ]]; then
      db_set harmony-ap/serversan "DNS:$(hostname -f)"
    fi
    db_input high harmony-ap/serversan || true
    db_go
  fi

  db_input high harmony-ap/tomcatport || true
  db_go

  db_beginblock
  DB_HOST="$(get_prop domibus.database.serverName)"
  if [[ -n "$DB_HOST" ]]; then
    db_set harmony-ap/database-host "$DB_HOST"
  fi
  db_input high harmony-ap/database-host
  DB_PORT="$(get_prop domibus.database.port)"
  if [[ -n "$DB_PORT" ]]; then
    db_set harmony-ap/database-port "$DB_PORT"
  fi
  db_input high harmony-ap/database-port
  DB_SCHEMA="$(get_prop domibus.database.schema)"
  if [[ -n "$DB_SCHEMA" ]]; then
    db_set harmony-ap/database-schema "$DB_SCHEMA"
  fi
  db_input high harmony-ap/database-schema
  db_endblock
  db_go

  db_get harmony-ap/database-schema
  DB_SCHEMA="$RET"

  db_beginblock
  DB_USER="$(get_prop domibus.database.user)"
  if [[ -n "$DB_USER" ]]; then
    db_set harmony-ap/database-user "$DB_USER"
  fi
  db_subst harmony-ap/database-user db_schema "$DB_SCHEMA"
  db_input high harmony-ap/database-user
  db_input high harmony-ap/database-password
  db_endblock
  db_go

fi

# TODO add some checking of values?
db_stop
